//! Mode → routing table, and the two sysctl/​drop-in side effects that go with it.
//!
//! # Strict `5g`: suppressing the ethernet gateway
//!
//! The IT admin asked for *only*, so metrics alone are not enough — a cable that
//! is plugged in must not carry traffic. The applier writes a drop-in on the
//! **effective** `.network` for `end0`, which is `pcat-ula`'s file, not
//! netplan's (landmine 5: only the first matching `.network` applies, and
//! `05-pcat-ula-end0.network` sorts ahead of netplan's `10-*`).
//!
//! `[IPv6AcceptRA] UseGateway=false` is load-bearing and was found by
//! measurement: without it the RA-learned IPv6 default route survives and strict
//! `5g` leaks IPv6 out of the ethernet. Both address families must be suppressed
//! together.
//!
//! **`Address=` is never touched**, so the DHCP lease, the fleet ULA and the
//! cockpit stay up throughout (NFR-NET-01). Measured in M0/O0.4 in both
//! directions: the two default routes disappear, both addresses stay, the
//! cockpit answers `200`/5266 B on the LAN IPv4 *and* the ULA, and removing the
//! drop-in restores everything.

use std::ffi::OsStr;
use std::path::{Path, PathBuf};

use super::apply::{Tools, WWAN_PROFILE, run, wan_iface};
use super::profiles;
use super::state::{NetworkConfig, Standby, UplinkMode};

/// The drop-in file name inside `05-pcat-ula-<if>.network.d/`.
const DROPIN_FILE: &str = "50-cp-uplink.conf";

/// Suppress both families' gateways. Anything less leaks (see the module doc).
const DROPIN_BODY: &str = "\
# Generated by the Context Pilot orchestrator — do not edit by hand.
# Strict `5g` uplink: keep every ADDRESS on this port (the DHCP lease and the
# fleet ULA — NFR-NET-01) but take away its default routes, so a plugged-in
# cable cannot carry traffic. Both families, or IPv6 leaks out of the ethernet.
[DHCPv4]
UseGateway=false
[DHCPv6]
UseGateway=false
[IPv6AcceptRA]
UseGateway=false
";

/// Where the drop-in lives, given the networkd config directory.
fn dropin_dir(networkd_dir: &Path) -> PathBuf {
    networkd_dir.join(format!("05-pcat-ula-{}.network.d", wan_iface()))
}

/// Write or remove the strict-`5g` drop-in and reconfigure `end0`.
///
/// Returns whether the on-disk state changed, so the caller can skip the
/// `networkctl` round-trip — reconfiguring regenerates the SLAAC privacy
/// addresses, which is cosmetic but pointless churn.
///
/// # Errors
///
/// Returns an I/O message when the drop-in cannot be written or removed.
fn sync_dropin(networkd_dir: &Path, wanted: bool) -> Result<bool, String> {
    let dir = dropin_dir(networkd_dir);
    let file = dir.join(DROPIN_FILE);
    let present = file.exists();
    if wanted == present {
        return Ok(false);
    }
    if wanted {
        std::fs::create_dir_all(&dir).map_err(|e| format!("create {}: {e}", dir.display()))?;
        std::fs::write(&file, DROPIN_BODY).map_err(|e| format!("write {}: {e}", file.display()))?;
    } else {
        std::fs::remove_file(&file).map_err(|e| format!("remove {}: {e}", file.display()))?;
    }
    Ok(true)
}

/// `networkctl reload && networkctl reconfigure <wan>`.
///
/// # Errors
///
/// Returns `networkctl`'s stderr.
fn reconfigure_wan(networkctl: &OsStr) -> Result<(), String> {
    let _reloaded = run(networkctl, &["reload".to_owned()])?;
    let _done = run(networkctl, &["reconfigure".to_owned(), wan_iface()])?;
    Ok(())
}

/// Apply the mode: the ethernet gateway suppression, then the bearer's activation.
///
/// **Bearer activation is best-effort and deliberately non-fatal.** Whether the
/// modem can attach is a fact about the world (coverage, SIM, antenna), not a
/// property of the setting the admin chose; failing the whole apply over it
/// would roll back a legitimate mode change and leave the admin unable to
/// express what they want. The failure is logged and shows up in
/// `GET /api/it/network`'s `wwan.state`, and NFR-NET-01 guarantees the cockpit
/// stays reachable on the LAN address and the fleet ULA, so the choice is always
/// reversible.
///
/// # Errors
///
/// Returns a message when the drop-in cannot be written or `networkctl` fails —
/// the parts that are genuinely under our control.
pub(crate) fn apply_mode(tools: &Tools, config: &NetworkConfig) -> Result<(), String> {
    if let Some(dir) = tools.networkd_dir.as_ref() {
        let strict = matches!(config.mode, UplinkMode::FiveG);
        if sync_dropin(dir, strict)? {
            if let Some(networkctl) = tools.networkctl.as_ref() {
                reconfigure_wan(networkctl)?;
            }
        }
    }
    let wanted_up = match config.mode {
        UplinkMode::Wan => false,
        UplinkMode::FiveG => true,
        // `hot` keeps the bearer connected at the standby metric so failover is
        // a metric flip; `cold` leaves it down and lets the supervisor pay the
        // setup cost at failover time.
        UplinkMode::WanThen5g => matches!(config.wwan.standby, Standby::Hot),
    };
    if let Err(failure) = profiles::set_active(&tools.nmcli, WWAN_PROFILE, wanted_up) {
        let verb = if wanted_up { "activation" } else { "deactivation" };
        eprintln!("network: {WWAN_PROFILE} {verb} (non-fatal): {failure}");
    }
    Ok(())
}

/// Bring the AP up or down, and put `net.ipv4.ip_forward` back where it belongs.
///
/// **NetworkManager sets `ip_forward=1` for `ipv4.method shared` and never
/// restores it** — measured in M0/O0.2: flipping to `manual` removed the `nft`
/// table and stopped dnsmasq, but left the sysctl at `1`. So restoring it is not
/// a nicety the applier may skip; it is the only thing that will ever put that
/// sysctl back, and leaving it at `1` silently keeps the box a router on the
/// client's LAN (landmine 6).
///
/// # Errors
///
/// Returns a message when the sysctl cannot be written.
pub(crate) fn apply_ap_activation(tools: &Tools, config: &NetworkConfig) -> Result<(), String> {
    if let Err(failure) = profiles::set_active(&tools.nmcli, super::apply::AP_PROFILE, config.ap.enabled) {
        // Same reasoning as the bearer: an rfkilled or absent radio must not
        // roll back a legitimate setting.
        eprintln!("network: {} (non-fatal): {failure}", super::apply::AP_PROFILE);
    }
    let sharing = config.ap.enabled && config.ap.share_internet;
    if !sharing {
        // The profile stays `ipv4.method shared` in both modes so dnsmasq keeps
        // handing out addresses (see `profiles::ap_args`). Dropping the
        // masquerade table is what turns it into a cul-de-sac, and it must
        // happen AFTER activation, which is when NetworkManager installs it.
        drop_nat_table(tools);
    }
    set_ip_forward(sharing)
}

/// Remove NetworkManager's `nm-shared-<iface>` masquerade table.
///
/// Best-effort and gated on `CP_NFT_BIN`: an absent table is the normal state,
/// not an error. Measured on hardware — after the delete, NM does **not** put it
/// back on its own, so the AP stays a cul-de-sac until the next activation, and
/// the next apply re-runs this anyway.
fn drop_nat_table(tools: &Tools) {
    let Some(nft) = tools.nft.as_ref() else {
        return;
    };
    let table = format!("nm-shared-{}", super::apply::ap_device());
    let args = ["delete".to_owned(), "table".to_owned(), "ip".to_owned(), table];
    // A "No such file or directory" here just means there was nothing to drop.
    let _dropped = run(nft, &args);
}

/// Write `net.ipv4.ip_forward` directly through `/proc`.
///
/// No `sysctl` binary needed, and no gate of its own: the file is either there
/// (Linux) or it is not (a dev laptop on another OS), and an absent file is a
/// clean no-op rather than an error.
///
/// # Errors
///
/// Returns a message when the file exists but cannot be written.
fn set_ip_forward(enabled: bool) -> Result<(), String> {
    let path = Path::new("/proc/sys/net/ipv4/ip_forward");
    if !path.exists() {
        return Ok(());
    }
    let wanted = if enabled { "1" } else { "0" };
    if std::fs::read_to_string(path).is_ok_and(|current| current.trim() == wanted) {
        return Ok(());
    }
    std::fs::write(path, format!("{wanted}\n")).map_err(|e| format!("set ip_forward={wanted}: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dropin_is_written_and_removed_idempotently() {
        let dir = tempfile::tempdir().expect("tempdir");
        let root = dir.path();
        // Absent → absent is a no-op, so the caller never reconfigures for nothing.
        assert_eq!(sync_dropin(root, false), Ok(false), "removing an absent drop-in changes nothing");
        assert_eq!(sync_dropin(root, true), Ok(true), "the first write changes state");
        let file = dropin_dir(root).join(DROPIN_FILE);
        let body = std::fs::read_to_string(&file).expect("read drop-in");
        // All three stanzas, or strict 5g leaks. The IPv6AcceptRA one was found
        // by measurement — the RA default route is independent of DHCPv4.
        assert!(body.contains("[DHCPv4]\nUseGateway=false"), "DHCPv4 gateway suppressed");
        assert!(body.contains("[DHCPv6]\nUseGateway=false"), "DHCPv6 gateway suppressed");
        assert!(body.contains("[IPv6AcceptRA]\nUseGateway=false"), "the RA default route is suppressed too");
        assert!(!body.contains("Address="), "NFR-NET-01: the drop-in never touches an address");

        assert_eq!(sync_dropin(root, true), Ok(false), "a second write changes nothing");
        assert_eq!(sync_dropin(root, true), Ok(false), "…and stays idempotent");
        assert_eq!(sync_dropin(root, false), Ok(true), "removal changes state");
        assert!(!file.exists(), "the drop-in is gone");
        assert_eq!(sync_dropin(root, false), Ok(false), "removing it twice changes nothing");
    }

    #[test]
    fn the_dropin_targets_the_pcat_ula_file_not_netplans() {
        // Landmine 5: only the FIRST matching .network applies, and pcat-ula's
        // per-port file sorts ahead of netplan's `10-netplan-all-eth-*`. A
        // drop-in on netplan's file would be silently ignored.
        let dir = dropin_dir(Path::new("/etc/systemd/network"));
        assert_eq!(dir, Path::new("/etc/systemd/network/05-pcat-ula-end0.network.d"));
    }
}
