//! Mode → routing table, and the two sysctl/​drop-in side effects that go with it.
//!
//! # Strict `5g`: suppressing the ethernet gateway
//!
//! The IT admin asked for *only*, so metrics alone are not enough — a cable that
//! is plugged in must not carry traffic. The applier writes a drop-in on the
//! **effective** `.network` for `end0`, which is `pcat-ula`'s file, not
//! netplan's: only the first matching `.network` applies, and
//! `05-pcat-ula-end0.network` sorts ahead of netplan's `10-*`. Any change to the
//! ULA generator must keep that drop-in directory, and any change to which
//! `.network` wins for `end0` invalidates the path below.
//!
//! `[IPv6AcceptRA] UseGateway=false` is load-bearing and was found by
//! measurement: without it the RA-learned IPv6 default route survives and strict
//! `5g` leaks IPv6 out of the ethernet. Both address families must be suppressed
//! together.
//!
//! **`Address=` is never touched**, so the DHCP lease, the fleet ULA and the
//! cockpit stay up throughout — no mode ever alters an address on the ethernet
//! ports, because they carry the fleet's only day-0 and break-glass access path.
//! MEASURED on hardware in both directions: the two default routes disappear,
//! both addresses stay, the cockpit answers `200`/5266 B on the LAN IPv4 *and*
//! the ULA, and removing the drop-in restores everything.

use std::ffi::OsStr;
use std::path::{Path, PathBuf};

use super::apply::{Tools, WWAN_PROFILE, run, wan_iface};
use super::state::{NetworkConfig, Standby, UplinkMode};

/// The drop-in file name inside `05-pcat-ula-<if>.network.d/`.
const DROPIN_FILE: &str = "50-cp-uplink.conf";

/// Suppress both families' gateways. Anything less leaks (see the module doc).
const DROPIN_BODY: &str = "\
# Generated by the Context Pilot orchestrator \u{2014} do not edit by hand.
# Strict `5g` uplink: keep every ADDRESS on this port (the DHCP lease and the
# fleet ULA) but take away its default routes, so a plugged-in
# cable cannot carry traffic. Both families, or IPv6 leaks out of the ethernet.
[DHCPv4]
UseGateway=false
[DHCPv6]
UseGateway=false
[IPv6AcceptRA]
UseGateway=false
";

/// Where the drop-in lives, given the networkd config directory.
fn dropin_dir(networkd_dir: &Path) -> PathBuf {
    networkd_dir.join(format!("05-pcat-ula-{}.network.d", wan_iface()))
}

/// Write or remove the strict-`5g` drop-in and reconfigure `end0`.
///
/// Returns whether the on-disk state changed, so the caller can skip the
/// `networkctl` round-trip — reconfiguring regenerates the SLAAC privacy
/// addresses, which is cosmetic but pointless churn.
///
/// # Errors
///
/// Returns an I/O message when the drop-in cannot be written or removed.
fn sync_dropin(networkd_dir: &Path, wanted: bool) -> Result<bool, String> {
    let dir = dropin_dir(networkd_dir);
    let file = dir.join(DROPIN_FILE);
    let present = file.exists();
    if wanted == present {
        return Ok(false);
    }
    if wanted {
        std::fs::create_dir_all(&dir).map_err(|e| format!("create {}: {e}", dir.display()))?;
        std::fs::write(&file, DROPIN_BODY).map_err(|e| format!("write {}: {e}", file.display()))?;
    } else {
        std::fs::remove_file(&file).map_err(|e| format!("remove {}: {e}", file.display()))?;
    }
    Ok(true)
}

/// `networkctl reload && networkctl reconfigure <wan>`.
///
/// # Errors
///
/// Returns `networkctl`'s stderr.
fn reconfigure_wan(networkctl: &OsStr) -> Result<(), String> {
    let _reloaded = run(networkctl, &["reload".to_owned()])?;
    let _done = run(networkctl, &["reconfigure".to_owned(), wan_iface()])?;
    Ok(())
}

/// Seconds `nmcli` may spend bringing a profile up or down before we stop
/// waiting on it. See [`set_active`] for why the default 90 s is unusable here.
const ACTIVATION_TIMEOUT_S: u32 = 20;

/// Bring a profile up or down, tolerating "already in that state".
///
/// `nmcli connection down` on an inactive profile and `up` on an active one both
/// exit non-zero, and neither is a failure of ours. Activation failures on the
/// bearer are also non-fatal by design — see [`super::apply`].
///
/// It lives here, beside its only two callers, rather than in
/// [`profiles`](super::profiles): that module *renders* the two profiles, this
/// one decides which of them should be running.
fn set_active(nmcli: &OsStr, profile: &str, active: bool) -> Result<(), String> {
    let verb = if active { "up" } else { "down" };
    // `--wait` is not a nicety. nmcli's default activation timeout is 90 s, and
    // a bearer with no coverage takes ALL of it — measured on hardware, where it
    // held an HTTP request (and the applier lock) open long enough for the
    // cockpit's button to look permanently frozen. Activation is best-effort
    // anyway (see [`apply_mode`]), so a bounded wait loses nothing: the AP came
    // up in 4 s when this was measured, and a modem that has not attached in
    // 20 s was not going to.
    let args = [
        "--wait".to_owned(),
        ACTIVATION_TIMEOUT_S.to_string(),
        "connection".to_owned(),
        verb.to_owned(),
        profile.to_owned(),
    ];
    match run(nmcli, &args) {
        Ok(_out) => Ok(()),
        // `nmcli connection down` on a profile that is already inactive exits
        // non-zero. That is the NORMAL state for both profiles on a box in
        // `wan` with the AP off, so treating it as a failure would put two
        // alarming lines in the journal on every single boot.
        Err(failure) if !active && failure.contains("not an active connection") => Ok(()),
        Err(failure) => Err(format!("{verb} {profile}: {failure}")),
    }
}

/// Apply the mode: the ethernet gateway suppression, then the bearer's activation.
///
/// **Bearer activation is best-effort and deliberately non-fatal.** Whether the
/// modem can attach is a fact about the world (coverage, SIM, antenna), not a
/// property of the setting the admin chose; failing the whole apply over it
/// would roll back a legitimate mode change and leave the admin unable to
/// express what they want. The failure is logged and shows up in
/// `GET /api/it/network`'s `wwan.state`, and since no mode ever alters an
/// address on the ethernet ports the cockpit stays reachable on the LAN address
/// and the fleet ULA, so the choice is always reversible.
///
/// Sync the systemd-networkd drop-in for the WAN uplink and reconfigure it when
/// the drop-in actually changed. Split out of [`apply_mode`] to keep that
/// function under the cognitive-complexity cap — this carries the nested
/// drop-in-write-then-reconfigure conditional on its own.
///
/// `strict` (5G mode) suppresses `end0`'s default route so the modem bearer
/// wins; `sync_dropin` returns `true` when it rewrote the file, and only then
/// do we ask `networkctl` to reload.
///
/// # Errors
///
/// Returns a message when the drop-in cannot be written or `networkctl` fails.
fn sync_networkd(tools: &Tools, config: &NetworkConfig) -> Result<(), String> {
    if let Some(dir) = tools.networkd_dir.as_ref() {
        let strict = matches!(config.mode, UplinkMode::FiveG);
        if sync_dropin(dir, strict)?
            && let Some(networkctl) = tools.networkctl.as_ref()
        {
            reconfigure_wan(networkctl)?;
        }
    }
    Ok(())
}

/// **"No modem ⇒ no 5G mode" is not enforced here** — `config.mode` has already
/// been coerced to `wan` by `apply::effective_config` if this box has no modem.
/// It used to be enforced by the `modem_present()` early-return below, which sits
/// *after* the drop-in is written: a document saying `5g` on a modem-less box
/// therefore suppressed `end0`'s default route at every boot with nothing to
/// replace it. Doing the coercion upstream makes that ordering bug structurally
/// impossible rather than a thing to remember; the check below now only guards
/// the activation of a profile that may not exist.
///
/// # Errors
///
/// Returns a message when the drop-in cannot be written or `networkctl` fails —
/// the parts that are genuinely under our control.
pub(crate) fn apply_mode(tools: &Tools, config: &NetworkConfig) -> Result<(), String> {
    sync_networkd(tools, config)?;
    let wanted_up = match config.mode {
        UplinkMode::Wan => false,
        UplinkMode::FiveG => true,
        // `hot` keeps the bearer connected at the standby metric so failover is
        // a metric flip; `cold` leaves it down and lets the supervisor pay the
        // setup cost at failover time.
        UplinkMode::WanThen5g => matches!(config.wwan.standby, Standby::Hot),
    };
    if !super::apply::modem_present() {
        return Ok(()); // no modem on this variant — nothing to bring up or down.
    }
    if let Err(failure) = set_active(&tools.nmcli, WWAN_PROFILE, wanted_up) {
        // At boot this reliably says "No suitable device found": the applier runs
        // before ModemManager has enumerated the modem, so NM has nothing to
        // bind the profile to. The profile carries `autoconnect yes` in both
        // modes that want it up, so NM brings it up by itself the moment the
        // device appears — which is why this is a note, not a failure.
        let verb = if wanted_up { "activation" } else { "deactivation" };
        crate::oerr!("network: {WWAN_PROFILE} {verb} deferred to NetworkManager ({failure})");
    }
    Ok(())
}

/// Bring the AP up or down, and put `net.ipv4.ip_forward` back where it belongs.
///
/// **`NetworkManager` sets `ip_forward=1` for `ipv4.method shared` and never
/// restores it** — MEASURED: flipping to `manual` removed the `nft` table and
/// stopped dnsmasq, but left the sysctl at `1`. So restoring it is not a nicety
/// the applier may skip; it is the only thing that will ever put that sysctl
/// back, and leaving it at `1` silently keeps the box a router on the client's
/// LAN — which is their IT's decision to make, not ours.
///
/// # Errors
///
/// Returns a message when the sysctl cannot be written.
pub(crate) fn apply_ap_activation(tools: &Tools, config: &NetworkConfig) -> Result<(), String> {
    if let Err(failure) = set_active(&tools.nmcli, super::apply::AP_PROFILE, config.ap.enabled) {
        // Same reasoning as the bearer: an rfkilled or absent radio must not
        // roll back a legitimate setting.
        crate::oerr!("network: {} (non-fatal): {failure}", super::apply::AP_PROFILE);
    }
    let sharing = config.ap.enabled && config.ap.share_internet;
    if !sharing {
        // The profile stays `ipv4.method shared` in both modes so dnsmasq keeps
        // handing out addresses (see `profiles::ap_args`). Dropping the
        // masquerade table is what turns it into a cul-de-sac, and it must
        // happen AFTER activation, which is when NetworkManager installs it.
        drop_nat_table(tools);
    }
    set_ip_forward(sharing)
}

/// Remove `NetworkManager`'s `nm-shared-<iface>` masquerade table.
///
/// Best-effort and gated on `CP_NFT_BIN`: an absent table is the normal state,
/// not an error. Measured on hardware — after the delete, NM does **not** put it
/// back on its own, so the AP stays a cul-de-sac until the next activation, and
/// the next apply re-runs this anyway.
fn drop_nat_table(tools: &Tools) {
    let Some(nft) = tools.nft.as_ref() else {
        return;
    };
    let table = format!("nm-shared-{}", super::apply::ap_device());
    let args = ["delete".to_owned(), "table".to_owned(), "ip".to_owned(), table];
    // A "No such file or directory" here just means there was nothing to drop.
    let _dropped = run(nft, &args);
}

/// Write `net.ipv4.ip_forward` directly through `/proc`.
///
/// No `sysctl` binary needed, and no gate of its own: the file is either there
/// (Linux) or it is not (a dev laptop on another OS), and an absent file is a
/// clean no-op rather than an error.
///
/// # Errors
///
/// Returns a message when the file exists but cannot be written.
fn set_ip_forward(enabled: bool) -> Result<(), String> {
    let path = Path::new("/proc/sys/net/ipv4/ip_forward");
    if !path.exists() {
        return Ok(());
    }
    let wanted = if enabled { "1" } else { "0" };
    if std::fs::read_to_string(path).is_ok_and(|current| current.trim() == wanted) {
        return Ok(());
    }
    std::fs::write(path, format!("{wanted}\n")).map_err(|e| format!("set ip_forward={wanted}: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dropin_is_written_and_removed_idempotently() {
        let dir = tempfile::tempdir().expect("tempdir");
        let root = dir.path();
        // Absent → absent is a no-op, so the caller never reconfigures for nothing.
        assert_eq!(sync_dropin(root, false), Ok(false), "removing an absent drop-in changes nothing");
        assert_eq!(sync_dropin(root, true), Ok(true), "the first write changes state");
        let file = dropin_dir(root).join(DROPIN_FILE);
        let body = std::fs::read_to_string(&file).expect("read drop-in");
        // All three stanzas, or strict 5g leaks. The IPv6AcceptRA one was found
        // by measurement — the RA default route is independent of DHCPv4.
        assert!(body.contains("[DHCPv4]\nUseGateway=false"), "DHCPv4 gateway suppressed");
        assert!(body.contains("[DHCPv6]\nUseGateway=false"), "DHCPv6 gateway suppressed");
        assert!(body.contains("[IPv6AcceptRA]\nUseGateway=false"), "the RA default route is suppressed too");
        assert!(!body.contains("Address="), "the drop-in never touches an address");

        assert_eq!(sync_dropin(root, true), Ok(false), "a second write changes nothing");
        assert_eq!(sync_dropin(root, true), Ok(false), "\u{2026}and stays idempotent");
        assert_eq!(sync_dropin(root, false), Ok(true), "removal changes state");
        assert!(!file.exists(), "the drop-in is gone");
        assert_eq!(sync_dropin(root, false), Ok(false), "removing it twice changes nothing");
    }

    #[test]
    fn the_dropin_targets_the_pcat_ula_file_not_netplans() {
        // Only the FIRST matching .network applies, and pcat-ula's
        // per-port file sorts ahead of netplan's `10-netplan-all-eth-*`. A
        // drop-in on netplan's file would be silently ignored.
        let dir = dropin_dir(Path::new("/etc/systemd/network"));
        assert_eq!(dir, Path::new("/etc/systemd/network/05-pcat-ula-end0.network.d"));
    }
}
