//! Both ends of the interface with `cp-uplink-watch`, the failover supervisor.
//!
//! The supervisor is the only part of this feature that is not Rust — it is a
//! POSIX shell daemon (`deploy/photonicat/network/cp-uplink-watch`) because it
//! must keep working when the box has no internet, and because `ip`, `ping` and
//! `nmcli` are the whole of what it does. It talks to the backend through two
//! files, and this module owns both of them:
//!
//! * **`/etc/default/cp-uplink`** (`CP_UPLINK_ENV`) — what we tell it. Written
//!   by [`write_uplink_env`] from the persisted document.
//! * **`/run/cp-uplink/state`** (`CP_UPLINK_STATE`) — what it tells us. Read by
//!   [`supervisor_status`] into the `status.supervisor` object.
//!
//! Keeping them together is the point: they are one contract, and every past
//! drift between the two — three variables the backend never rendered, a state
//! file nothing opened — was a drift between two files that lived nowhere near
//! each other.

use std::path::PathBuf;

use serde_json::{Value, json};

use super::apply::{Tools, WWAN_PROFILE, run, wan_iface, wwan_device};
use super::state::{NetworkConfig, ProbeConfig};

// ── What we tell the supervisor ─────────────────────────────────────────────

/// Render `/etc/default/cp-uplink` and restart the supervisor when it changed.
///
/// Only on change: the supervisor is the thing that restores
/// connectivity, and bouncing it on every unrelated save would drop its
/// hysteresis state and re-arm the cooldown for nothing.
///
/// # Errors
///
/// Returns a message when the file cannot be written.
pub(crate) fn write_uplink_env(tools: &Tools, config: &NetworkConfig) -> Result<(), String> {
    let Some(path) = tools.uplink_env.as_ref() else {
        return Ok(());
    };
    let body = render_uplink_env(config);
    if std::fs::read_to_string(path).is_ok_and(|current| current == body) {
        return Ok(());
    }
    std::fs::write(path, &body).map_err(|e| format!("write {}: {e}", path.display()))?;
    if let Some(systemctl) = tools.systemctl.as_ref() {
        let args = ["restart".to_owned(), "cp-uplink.service".to_owned()];
        if let Err(failure) = run(systemctl, &args) {
            eprintln!("network: could not restart cp-uplink (non-fatal): {failure}");
        }
    }
    Ok(())
}

/// The supervisor's environment file — a plain `KEY=value` list sourced by the
/// unit, in the same spirit as `/etc/default/pcat-ula`.
///
/// Every variable `cp-uplink-watch` reads is written here. The three timing
/// knobs were the exception for a while: with no field in [`ProbeConfig`] to
/// render them they were permanently 3 s / 60 s / 20 s and unreachable from the
/// cockpit, which in particular made the cooldown meaningless the moment
/// `interval_s` was raised past 60.
///
/// [`ProbeConfig`]: super::state::ProbeConfig
pub(crate) fn render_uplink_env(config: &NetworkConfig) -> String {
    let mut out = String::from("# Generated by the Context Pilot orchestrator \u{2014} do not edit by hand.\n");
    out.push_str(&format!("CP_UPLINK_MODE={}\n", config.mode.as_str()));
    out.push_str(&format!("CP_UPLINK_WAN_IF={}\n", wan_iface()));
    out.push_str(&format!("CP_UPLINK_WWAN_PROFILE={WWAN_PROFILE}\n"));
    out.push_str(&format!("CP_UPLINK_WWAN_DEV={}\n", wwan_device()));
    out.push_str(&format!("CP_UPLINK_STANDBY={}\n", config.wwan.standby.as_str()));
    out.push_str(&format!("CP_UPLINK_TARGETS=\"{}\"\n", config.probe.targets.join(" ")));
    out.push_str(&format!("CP_UPLINK_FAIL_THRESHOLD={}\n", config.probe.fail_threshold));
    out.push_str(&format!("CP_UPLINK_OK_THRESHOLD={}\n", config.probe.ok_threshold));
    out.push_str(&format!("CP_UPLINK_INTERVAL_S={}\n", config.probe.interval_s));
    out.push_str(&format!("CP_UPLINK_PROBE_TIMEOUT_S={}\n", config.probe.probe_timeout_s));
    out.push_str(&format!("CP_UPLINK_COOLDOWN_S={}\n", config.probe.cooldown_s));
    out.push_str(&format!("CP_UPLINK_NM_WAIT_S={}\n", config.probe.nm_wait_s));
    out.push_str(&format!("CP_UPLINK_METRIC_PREFERRED={}\n", super::apply::METRIC_PREFERRED));
    out.push_str(&format!("CP_UPLINK_METRIC_STANDBY={}\n", super::apply::METRIC_STANDBY));
    out
}

// ── What the supervisor can honour ─────────────────────────────────────────

/// Validate the probe tuning. Zero thresholds would make the supervisor either
/// never fail over or fail over on the first dropped packet; a zero interval
/// would spin.
///
/// # Errors
///
/// Returns a human-readable reason when a field is out of range.
pub(super) fn validate_probe(probe: &ProbeConfig) -> Result<(), String> {
    if probe.targets.is_empty() {
        return Err("at least one probe target is required".to_owned());
    }
    if probe.targets.iter().any(|target| target.parse::<std::net::IpAddr>().is_err()) {
        return Err("probe targets must be IP addresses".to_owned());
    }
    if probe.fail_threshold == 0 || probe.ok_threshold == 0 {
        return Err("probe thresholds must be at least 1".to_owned());
    }
    if !(1..=3600).contains(&probe.interval_s) {
        return Err("probe interval must be between 1 and 3600 seconds".to_owned());
    }
    validate_probe_timing(probe)
}

/// The three seconds-valued supervisor knobs, split out of
/// [`validate_probe`] to keep either function inside the complexity budget.
///
/// The ranges are what the supervisor can actually honour, not taste:
/// `probe_timeout_s` is paid once per target per round, and `nm_wait_s` is a
/// bounded replacement for nmcli's unusable 90 s default — `routes::set_active`
/// pays the same measured cost on the applier side.
///
/// **A `cooldown_s` below `interval_s` is deliberately legal.** It simply never
/// binds: the supervisor evaluates the cooldown once per round, so a cooldown
/// shorter than a round has always elapsed by the time it is read. That is a
/// coherent way to spell "no hysteresis beyond the streak thresholds", and
/// refusing the combination would make the two fields fight for no reason.
///
/// # Errors
///
/// Returns a human-readable reason when a field is out of range.
fn validate_probe_timing(probe: &ProbeConfig) -> Result<(), String> {
    if !(1..=60).contains(&probe.probe_timeout_s) {
        return Err("probe timeout must be between 1 and 60 seconds".to_owned());
    }
    if !(1..=3600).contains(&probe.cooldown_s) {
        return Err("failover cooldown must be between 1 and 3600 seconds".to_owned());
    }
    if !(1..=120).contains(&probe.nm_wait_s) {
        return Err("NetworkManager wait must be between 1 and 120 seconds".to_owned());
    }
    Ok(())
}

// ── What the supervisor tells us ────────────────────────────────────────────

/// Where `cp-uplink-watch` publishes its state, `CP_UPLINK_STATE`-gated like
/// every other path this feature touches.
fn uplink_state_path() -> PathBuf {
    std::env::var_os("CP_UPLINK_STATE").map_or_else(|| PathBuf::from("/run/cp-uplink/state"), PathBuf::from)
}

/// The supervisor's published state, or `null` when it has published none.
///
/// # Why this is read at all
///
/// `cp-uplink-watch` rewrites this file every probe round and, until now,
/// **nothing opened it** — while `cp-uplink.service`'s own header stated as fact
/// that the cockpit reads it. It carries the four things
/// `/proc/net/route` structurally cannot express, and they are exactly what an
/// admin wants during a failover: whether the supervisor is running at all,
/// whether *it* decided to promote the bearer (as opposed to what the kernel
/// happens to show), why, and when. The route table shows the outcome; this
/// shows the decision, and the gap between the two is the whole diagnosis.
pub(crate) fn supervisor_status() -> Value {
    std::fs::read_to_string(uplink_state_path()).map_or(Value::Null, |body| parse_uplink_state(&body))
}

/// Parse the supervisor's shell-sourceable `KEY=value` file.
///
/// Tolerant in exactly the way the `nmcli -t` parsers are: unknown keys are
/// ignored, missing keys take their default, and a value that will not parse
/// takes its default rather than failing the whole read. That tolerance is what
/// lets the shell side add a key — `achieved` is being added for the "decided
/// but could not be carried out" case — without a flag-day change. An absent
/// `achieved` therefore reads as `true`: the older script only ever recorded
/// decisions it believed had succeeded.
///
/// `null` only when not one recognised key is present, which is the difference
/// between "the supervisor has not written yet" and "it wrote something we do
/// not fully understand".
fn parse_uplink_state(body: &str) -> Value {
    let mut state = UplinkState::default();
    let mut recognised = false;
    for line in body.lines() {
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        recognised |= state.absorb(key.trim(), value.trim());
    }
    if !recognised {
        return Value::Null;
    }
    json!({
        "supervising": state.supervising,
        "promoted": state.promoted,
        "achieved": state.achieved,
        "active_uplink": state.active_uplink,
        "fail_streak": state.fail_streak,
        "ok_streak": state.ok_streak,
        "last_transition": state.last_transition.map_or(Value::Null, |at| json!(at)),
        "last_reason": state.last_reason.map_or(Value::Null, |reason| json!(reason)),
    })
}

/// Re-check the supervisor's **already-classified** `active_uplink` word against
/// our four values.
///
/// Not `status::classify_device`: this file holds `wan`/`wwan`/`other`/`none`,
/// not an interface name — `cp-uplink-watch` runs its own `classify_dev` before
/// writing. Passing an unrecognised word through as `other` is what keeps the
/// response's enum closed whatever version of the script is installed.
fn normalise_uplink(word: &str) -> &'static str {
    match word {
        "wan" => "wan",
        "wwan" => "wwan",
        "none" | "" => "none",
        _unknown => "other",
    }
}

/// The keys of `/run/cp-uplink/state` this projection understands, pre-loaded
/// with the answer for a supervisor that has said nothing about them.
struct UplinkState {
    /// Whether the supervisor considers this mode worth supervising at all.
    supervising: bool,
    /// Whether **it** decided the bearer should be the uplink.
    promoted: bool,
    /// Whether that decision could actually be carried out. Defaults to `true`
    /// so a script predating the key does not read as permanently failing.
    achieved: bool,
    /// What the kernel actually shows, in the same four values as
    /// `status::active_uplink`.
    active_uplink: &'static str,
    /// Consecutive failed probe rounds.
    fail_streak: u32,
    /// Consecutive successful probe rounds.
    ok_streak: u32,
    /// Unix seconds of the last transition. `0` in the file means "never" and
    /// becomes `None`, because 1970-01-01 is not a useful thing to render.
    last_transition: Option<u64>,
    /// The sentence the supervisor logged for that transition.
    last_reason: Option<String>,
}

impl Default for UplinkState {
    fn default() -> Self {
        Self {
            supervising: false,
            promoted: false,
            achieved: true,
            active_uplink: "none",
            fail_streak: 0,
            ok_streak: 0,
            last_transition: None,
            last_reason: None,
        }
    }
}

impl UplinkState {
    /// Absorb one `key=value` line, reporting whether the key was one of ours.
    ///
    /// `last_reason` takes the rest of the line verbatim — it is a sentence and
    /// contains spaces — which is also why the split is on the **first** `=`.
    fn absorb(&mut self, key: &str, value: &str) -> bool {
        match key {
            "supervising" => self.supervising = value == "yes",
            "promoted" => self.promoted = value == "yes",
            "achieved" => self.achieved = value != "no",
            "active_uplink" => self.active_uplink = normalise_uplink(value),
            "fail_streak" => self.fail_streak = value.parse().unwrap_or_default(),
            "ok_streak" => self.ok_streak = value.parse().unwrap_or_default(),
            "last_transition" => self.last_transition = value.parse().ok().filter(|&at| at != 0),
            "last_reason" => self.last_reason = (!value.is_empty()).then(|| value.to_owned()),
            _other => return false,
        }
        true
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A realistic `/run/cp-uplink/state`, mid-failover, byte-for-byte in
    /// the shape `write_state` emits.
    #[test]
    fn the_supervisors_own_state_is_parsed() {
        let file = "\
mode=wan_5g
supervising=yes
active_uplink=wwan
promoted=yes
achieved=yes
fail_streak=0
ok_streak=1
last_transition=1753800000
last_reason=end0 unreachable for 3 consecutive probes
";
        let state = parse_uplink_state(file);
        assert_eq!(state.get("supervising"), Some(&json!(true)));
        assert_eq!(state.get("promoted"), Some(&json!(true)));
        assert_eq!(state.get("achieved"), Some(&json!(true)));
        assert_eq!(state.get("active_uplink"), Some(&json!("wwan")));
        assert_eq!(state.get("fail_streak"), Some(&json!(0)));
        assert_eq!(state.get("ok_streak"), Some(&json!(1)));
        assert_eq!(state.get("last_transition"), Some(&json!(1_753_800_000u64)));
        // The reason is a sentence: everything after the FIRST `=` is its value.
        assert_eq!(state.get("last_reason"), Some(&json!("end0 unreachable for 3 consecutive probes")));
        // `mode` is not part of this projection: ignored, not fatal.
        assert_eq!(state.get("mode"), None);
    }

    /// The same tolerance the `nmcli -t` parsers apply: missing keys default,
    /// `last_transition=0` means never, an unknown value keeps the enum closed,
    /// and a file with nothing recognisable is `null` rather than an object full
    /// of invented zeroes.
    #[test]
    fn a_startup_state_file_degrades_key_by_key() {
        let startup =
            "supervising=no\npromoted=no\nfail_streak=0\nok_streak=0\nlast_transition=0\nlast_reason=startup\n";
        let state = parse_uplink_state(startup);
        assert_eq!(state.get("last_transition"), Some(&Value::Null), "0 means never, not 1970");
        assert_eq!(state.get("active_uplink"), Some(&json!("none")), "an absent key takes its default");
        assert_eq!(state.get("achieved"), Some(&json!(true)), "a script predating the key is not 'failing'");

        // The key the shell side is adding for "decided but not achieved",
        // read as written.
        assert_eq!(parse_uplink_state("promoted=yes\nachieved=no\n").get("achieved"), Some(&json!(false)));

        // A word this build does not know must not widen the response's enum.
        assert_eq!(parse_uplink_state("active_uplink=carrier-pigeon").get("active_uplink"), Some(&json!("other")));

        assert_eq!(parse_uplink_state(""), Value::Null, "no content \u{21d2} nothing to report");
        assert_eq!(parse_uplink_state("# just a comment\n"), Value::Null, "\u{2026}and neither is a comment");
    }

    /// The bounds on the three timing knobs are what the supervisor can
    /// actually honour, so they are asserted against the validator itself.
    #[test]
    fn the_supervisor_knobs_are_bounded_by_what_it_can_honour() {
        assert!(validate_probe(&ProbeConfig::default()).is_ok(), "the shipped defaults are legal");

        let out_of_range: [(&str, fn(&mut ProbeConfig)); 6] = [
            ("a zero probe timeout", |probe| probe.probe_timeout_s = 0),
            ("a probe timeout above 60 s", |probe| probe.probe_timeout_s = 61),
            ("a zero cooldown", |probe| probe.cooldown_s = 0),
            ("a cooldown above an hour", |probe| probe.cooldown_s = 3601),
            ("a zero nmcli wait", |probe| probe.nm_wait_s = 0),
            ("an nmcli wait above 120 s", |probe| probe.nm_wait_s = 121),
        ];
        for (label, mutate) in out_of_range {
            let mut probe = ProbeConfig::default();
            mutate(&mut probe);
            assert!(validate_probe(&probe).is_err(), "{label} must be refused");
        }

        // A cooldown BELOW the interval is legal: it simply never binds, which
        // is a coherent way to spell "no hysteresis beyond the streak
        // thresholds". Refusing it would make the two fields fight for nothing.
        let mut never_binds = ProbeConfig::default();
        never_binds.interval_s = 120;
        never_binds.cooldown_s = 30;
        assert!(validate_probe(&never_binds).is_ok(), "a never-binding cooldown is a choice, not an error");
    }

    /// The three knobs that once had no line at all. `cp-uplink-watch` reads
    /// every one of these names; before this they were dead defaults in the
    /// script and unreachable from the cockpit.
    #[test]
    fn the_supervisors_env_file_renders_every_knob_it_reads() {
        let mut config = NetworkConfig::default();
        config.probe.probe_timeout_s = 5;
        config.probe.cooldown_s = 120;
        config.probe.nm_wait_s = 45;
        let body = render_uplink_env(&config);
        assert!(body.contains("\nCP_UPLINK_PROBE_TIMEOUT_S=5\n"), "{body}");
        assert!(body.contains("\nCP_UPLINK_COOLDOWN_S=120\n"), "{body}");
        assert!(body.contains("\nCP_UPLINK_NM_WAIT_S=45\n"), "{body}");
        // …and the ones that were always there still are.
        for expected in ["CP_UPLINK_MODE=wan", "CP_UPLINK_STANDBY=hot", "CP_UPLINK_INTERVAL_S=10"] {
            assert!(body.contains(expected), "{expected} missing from: {body}");
        }
        assert!(body.contains("CP_UPLINK_TARGETS=\"1.1.1.1 9.9.9.9\""), "targets are space-joined and quoted");
    }
}
