//! Appliance-only gates: Caddy, the network applier, the uplink supervisor.
//!
//! Every path here is a *gate*: absent, the matching integration is inert and
//! the orchestrator only persists the document. A container or a developer
//! machine must leave all of them unset.

use crate::spec::{Exist, Fallback, Group, Kind, Scope, Spec};

/// One executable gate.
const fn tool(name: &'static str, doc: &'static str) -> Spec {
    Spec {
        name,
        kind: Kind::Path(Exist::Executable),
        fallback: Fallback::None,
        scope: Scope::Orchestrator,
        group: Group::Appliance,
        doc,
        ..Spec::BASE
    }
}

/// Appliance gates.
pub(super) static SPECS: &[Spec] = &[
    // ── Caddy / TLS ─────────────────────────────────────────────────────
    Spec {
        name: "CP_CADDYFILE",
        kind: Kind::Path(Exist::Parent),
        fallback: Fallback::None,
        scope: Scope::Orchestrator,
        group: Group::Appliance,
        doc: "Caddyfile the orchestrator regenerates (box name and IP, provisioned gate: cleartext :80 at day-0, private-CA :443 once provisioned). Unset, Caddy is never touched.",
        ..Spec::BASE
    },
    tool("CP_CADDY_BIN", "Caddy binary used to reload the regenerated Caddyfile. Requires `CP_CADDYFILE`."),
    Spec {
        name: "CP_CA_ROOT",
        kind: Kind::Path(Exist::No),
        fallback: Fallback::None,
        scope: Scope::Orchestrator,
        group: Group::Appliance,
        doc: "Root certificate of the private CA, served for download at `/api/it/ca.crt`. Caddy creates it on first TLS use, so it need not exist at boot.",
        ..Spec::BASE
    },
    // ── Network applier ─────────────────────────────────────────────────
    tool(
        "CP_NMCLI_BIN",
        "`nmcli` - the master gate of the network applier. Unset, the applier is inert (documents are persisted, never applied) and the modem is assumed present.",
    ),
    tool("CP_MMCLI_BIN", "`mmcli` - modem status for `GET /api/it/network`."),
    tool("CP_IW_BIN", "`iw` - Wi-Fi radio capabilities and regulatory domain."),
    tool("CP_IP_BIN", "`ip` - interface addresses for the network status."),
    tool("CP_NETWORKCTL_BIN", "`networkctl` - reload of systemd-networkd after writing its units."),
    tool("CP_SYSTEMCTL_BIN", "`systemctl` - restart of the uplink supervisor after its configuration changes."),
    tool("CP_NFT_BIN", "`nft` - NAT rules for the access-point clients."),
    tool(
        "CP_REGDOM_BIN",
        "The `cp-regdom` script that puts the Wi-Fi country in force (shared with the boot oneshot).",
    ),
    Spec {
        name: "CP_NETWORKD_DIR",
        kind: Kind::Path(Exist::Dir),
        fallback: Fallback::None,
        scope: Scope::Orchestrator,
        group: Group::Appliance,
        doc: "Directory of the systemd-networkd units the applier writes (`/etc/systemd/network`).",
        ..Spec::BASE
    },
    Spec {
        name: "CP_UPLINK_ENV",
        kind: Kind::Path(Exist::Parent),
        fallback: Fallback::None,
        scope: Scope::Orchestrator,
        group: Group::Appliance,
        doc: "Environment file of the uplink supervisor (`/etc/default/cp-uplink`), regenerated by the applier and read by `cp-uplink-watch`.",
        ..Spec::BASE
    },
    Spec {
        name: "CP_UPLINK_STATE",
        kind: Kind::Path(Exist::No),
        fallback: Fallback::Literal("/run/cp-uplink/state"),
        scope: Scope::Orchestrator,
        group: Group::Appliance,
        doc: "State file published by `cp-uplink-watch` and projected by `GET /api/it/network`. Both sides read the same name with the same default.",
        ..Spec::BASE
    },
    Spec {
        name: "CP_NETWORK_APPLIED",
        kind: Kind::Path(Exist::No),
        fallback: Fallback::Literal("/run/cp-network-applied"),
        scope: Scope::Orchestrator,
        group: Group::Appliance,
        doc: "Marker recording the hash of the last applied network document, so a hand edit is reverted at the next apply or boot.",
        ..Spec::BASE
    },
    // ── Hardware names ──────────────────────────────────────────────────
    Spec {
        name: "CP_WAN_IFACE",
        kind: Kind::Str,
        fallback: Fallback::Literal("end0"),
        scope: Scope::Orchestrator,
        group: Group::Appliance,
        doc: "The Ethernet uplink port.",
        ..Spec::BASE
    },
    Spec {
        name: "CP_AP_IFACE",
        kind: Kind::Str,
        fallback: Fallback::Literal("wlp1s0"),
        scope: Scope::Orchestrator,
        group: Group::Appliance,
        doc: "The Wi-Fi radio used for the access point.",
        ..Spec::BASE
    },
    Spec {
        name: "CP_WWAN_DEV",
        kind: Kind::Str,
        fallback: Fallback::Literal("cdc-wdm0"),
        scope: Scope::Orchestrator,
        group: Group::Appliance,
        doc: "The modem's NetworkManager device (its control port).",
        ..Spec::BASE
    },
    Spec {
        name: "CP_WWAN_PRESENT",
        kind: Kind::Bool,
        fallback: Fallback::None,
        scope: Scope::Orchestrator,
        group: Group::Appliance,
        doc: "Force whether a 5G modem is present (1) or absent (0) instead of probing the hardware. Field debugging only.",
        ..Spec::BASE
    },
];
