//! First-run bootstrap for the Tuwunel homeserver.
//!
//! Creates the data directory layout, generates a minimal
//! `homeserver.toml`, writes a credentials placeholder, generates
//! per-bridge config templates, and ensures the Tuwunel binary is
//! present (downloading it on first run).

use std::fmt::Write as _;
use std::path::Path;

use cp_base::state::runtime::State;

use crate::client::account;
use crate::server;
use crate::types::ChatState;

/// Name used as the Matrix server name in local-only mode.
const SERVER_NAME: &str = "localhost";

/// Default bot account localpart.
const BOT_LOCALPART: &str = "context-pilot";

/// Run the first-time bootstrap sequence.
///
/// Creates the directory tree under `.context-pilot/matrix/`, writes
/// `homeserver.toml` with secure defaults, and scaffolds support files.
/// Skips any step whose output already exists (safe to call repeatedly).
///
/// # Errors
///
/// Returns a description of the first I/O failure encountered.
pub(crate) fn bootstrap(project_root: &Path) -> Result<(), String> {
    let data = server::data_dir(project_root);
    let cfg = server::config_path(project_root);

    // 0. Ensure the Tuwunel binary is present (download if missing)
    crate::client::download::ensure_binary()?;

    // 1. Create directory tree
    create_dirs(&data)?;

    // 2. Write homeserver.toml (only if absent)
    if !cfg.exists() {
        write_config(&cfg, &data)?;
    }

    // 3. Write credentials placeholder (only if absent)
    let creds = data.join("credentials.json");
    if !creds.exists() {
        write_credentials_placeholder(&creds)?;
    }

    // 4. Generate per-bridge config.yaml templates (only if absent)
    crate::bridges::generate_bridge_configs(project_root)?;

    Ok(())
}

/// Post-start setup: register the bot account, store credentials,
/// and create the default `#general` room.
///
/// Runs once after the server becomes healthy. Skips steps that are
/// already complete (idempotent). Reads `credentials.json` — if the
/// access token is already populated, nothing happens.
///
/// # Errors
///
/// Returns a description of the first failure encountered.
pub(crate) fn post_start_setup(state: &mut State) -> Result<(), String> {
    let root = Path::new(".");
    let data = server::data_dir(root);
    let creds_path = data.join("credentials.json");

    // Load existing credentials to check if registration already done
    let existing = account::load_credentials(&creds_path)?;
    if !existing.access_token.is_empty() {
        // Already registered — just propagate to ChatState
        let cs = ChatState::get_mut(state);
        cs.bot_user_id = Some(existing.user_id);
        return Ok(());
    }

    // 1. Register the bot account on the homeserver
    let creds = account::register_bot_account()?;

    // 2. Persist the credentials
    account::save_credentials(&creds_path, &creds)?;

    // 3. Store user ID in ChatState for immediate use
    let cs = ChatState::get_mut(state);
    cs.bot_user_id = Some(creds.user_id.clone());

    // 4. Create default #general room (best-effort — not fatal)
    if let Err(e) = account::create_default_room(&creds.access_token) {
        log::warn!("Failed to create default room: {e}");
    }

    // 5. Set bot display name (best-effort — not fatal)
    if let Err(e) = account::set_bot_display_name(&creds.access_token, account::BOT_DISPLAY_NAME) {
        log::warn!("Failed to set display name: {e}");
    }

    // 6. Register any detected bridge appservice files with the homeserver
    match crate::bridges::update_appservice_registrations(root) {
        Ok(true) => log::info!("Updated homeserver appservice registrations"),
        Ok(false) => {} // No new registrations found
        Err(e) => log::warn!("Failed to update appservice registrations: {e}"),
    }

    Ok(())
}

// -- Directory and config scaffolding ----------------------------------------

/// Create the matrix data directory tree.
fn create_dirs(data: &Path) -> Result<(), String> {
    for sub in &["data", "media", "bridges"] {
        let p = data.join(sub);
        std::fs::create_dir_all(&p).map_err(|e| format!("Cannot create {}: {e}", p.display()))?;
    }
    Ok(())
}

/// Write a minimal `homeserver.toml` with localhost-only defaults.
///
/// Uses `RocksDB` (Tuwunel's default and only backend) with data stored
/// in the project-local `.context-pilot/matrix/data/` directory.
/// Registration is enabled with a token so the bot account can be
/// created programmatically during [`post_start_setup`].
fn write_config(path: &Path, data_dir: &Path) -> Result<(), String> {
    let db_path = data_dir.join("db");
    let db_str = db_path.to_string_lossy();
    let reg_token = account::generate_registration_token();
    let port = server::derive_port();

    let mut cfg = String::with_capacity(512);

    {
        let _r = writeln!(cfg, "# Tuwunel homeserver configuration");
    }
    {
        let _r = writeln!(cfg, "# Auto-generated by Context Pilot. Edit with care.");
    }
    {
        let _r = writeln!(cfg);
    }
    {
        let _r = writeln!(cfg, "[global]");
    }
    {
        let _r = writeln!(cfg, "server_name = \"{SERVER_NAME}\"");
    }
    {
        let _r = writeln!(cfg, "port = [{port}]");
    }
    {
        let _r = writeln!(cfg, "address = \"127.0.0.1\"");
    }
    {
        let _r = writeln!(cfg, "database_path = \"{db_str}\"");
    }
    {
        let _r = writeln!(cfg, "allow_registration = true");
    }
    {
        let _r = writeln!(cfg, "registration_token = \"{reg_token}\"");
    }
    {
        let _r = writeln!(cfg, "allow_federation = false");
    }
    {
        let _r = writeln!(cfg, "trusted_servers = []");
    }

    std::fs::write(path, cfg).map_err(|e| format!("Cannot write {}: {e}", path.display()))
}

/// Write a JSON placeholder for bot credentials.
///
/// The actual access token is populated after the bot account is
/// registered with the running homeserver (§2 task X439).
fn write_credentials_placeholder(path: &Path) -> Result<(), String> {
    let json = format!(
        "{{\n  \"user_id\": \"@{BOT_LOCALPART}:{SERVER_NAME}\",\n  \"access_token\": \"\",\n  \"device_id\": \"\"\n}}\n"
    );
    std::fs::write(path, json).map_err(|e| format!("Cannot write {}: {e}", path.display()))
}
