[package]
name = "cp-mod-utilities"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Lightweight utility replacements for external dependencies"
readme.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]

[lints]
workspace = true
