use crate::state::persistence::log_error;
use crate::state::{Kind, State, StreamPhase, estimate_tokens};
use cp_base::state::data::model_helpers::{ModelPricing as _, token_cost};

use super::ActionResult;
use super::helpers::clean_llm_id_prefix;

/// Handle `AppendChars` action — append streaming text to assistant message.
pub(crate) fn handle_append_chars(state: &mut State, text: &str) -> ActionResult {
    if let Some(msg) = state.messages.last_mut()
        && msg.role == "assistant"
    {
        msg.content.push_str(text);

        // Update estimated token count during streaming
        let new_estimate = estimate_tokens(&msg.content);
        let added = new_estimate.saturating_sub(state.streaming_estimated_tokens);

        if added > 0 {
            if let Some(ctx) = state.context.iter_mut().find(|c| c.context_type.as_str() == Kind::CONVERSATION) {
                ctx.token_count = ctx.token_count.saturating_add(added);
            }
            state.streaming_estimated_tokens = new_estimate;
        }
    }
    ActionResult::Nothing
}

/// Token usage reported when a stream completes.
struct TokenUsage {
    /// Number of output tokens generated.
    output: usize,
    /// Number of cache-hit input tokens.
    cache_hit: usize,
    /// Number of cache-miss input tokens (`cache_creation` + uncached input).
    cache_miss: usize,
    /// Uncached input tokens (after last cache breakpoint, billed at base price).
    /// Already folded into `cache_miss` — tracked separately for display.
    uncached_input: usize,
}

/// Per-stream cost in USD, frozen at the producing model's pricing.
struct StreamCost {
    /// Cache-hit cost in USD for this stream.
    hit: f64,
    /// Cache-miss (incl. uncached input) cost in USD for this stream.
    miss: f64,
    /// Output cost in USD for this stream.
    output: f64,
}

/// Aggregated fields from the LLM API response when a stream finishes.
///
/// Each field maps 1:1 to an API response field, bundled to avoid
/// excessive parameter counts on [`handle_stream_done`].
pub(crate) struct StreamDoneEvent<'ev> {
    /// Total input tokens consumed by the request.
    pub input_tokens: usize,
    /// Total output tokens generated by the model.
    pub output_tokens: usize,
    /// Input tokens served from the prompt cache.
    pub cache_hit: usize,
    /// Input tokens that missed the prompt cache.
    pub cache_miss: usize,
    /// Model-reported stop reason, if any (e.g. `"end_turn"`).
    pub stop_reason: Option<&'ev str>,
}

/// Handle `StreamDone` action — finalize streaming, correct token counts.
pub(crate) fn handle_stream_done(state: &mut State, event: &StreamDoneEvent<'_>) -> ActionResult {
    state.flags.stream.phase.transition(StreamPhase::Idle);
    state.last_stop_reason = event.stop_reason.map(str::to_owned);

    let usage = TokenUsage {
        output: event.output_tokens,
        cache_hit: event.cache_hit,
        // Uncached input tokens (after the last cache breakpoint) are billed at base input price.
        // Folding them into cache_miss ensures the cost display accounts for all input costs.
        cache_miss: event.cache_miss.saturating_add(event.input_tokens),
        uncached_input: event.input_tokens,
    };

    // Cost is frozen here, at the price of the model that produced THIS response.
    // Accumulating dollars (not recomputing tokens × current price later) keeps past
    // spend stable when the user switches models afterwards.
    let cost = StreamCost {
        hit: token_cost(usage.cache_hit, state.cache_hit_price_per_mtok()),
        miss: token_cost(event.cache_miss, state.cache_miss_price_per_mtok())
            + token_cost(event.input_tokens, state.input_price_per_mtok()),
        output: token_cost(usage.output, state.output_price_per_mtok()),
    };
    apply_token_usage(state, &usage, &cost);

    // Append per-tick cost row (consumes tick_telemetry populated at stream start)
    crate::app::run::tools::cost_log::append_cost_tsv(state);

    // Correct the estimated tokens with actual output tokens on Conversation context and update timestamp
    if let Some(ctx) = state.context.iter_mut().find(|c| c.context_type.as_str() == Kind::CONVERSATION) {
        // Remove our estimate, add actual
        ctx.token_count =
            ctx.token_count.saturating_sub(state.streaming_estimated_tokens).saturating_add(event.output_tokens);
        ctx.last_refresh_ms = crate::app::panels::now_ms();
    }
    state.streaming_estimated_tokens = 0;

    // Store actual token count on message and clean up LLM prefixes
    if let Some(msg) = state.messages.last_mut()
        && msg.role == "assistant"
    {
        // Remove any [A##]: prefixes the LLM mistakenly added
        msg.content = clean_llm_id_prefix(&msg.content);
        msg.content_token_count = event.output_tokens;
        msg.input_tokens = event.input_tokens;
        let id = msg.id.clone();
        return ActionResult::SaveMessage(id);
    }
    ActionResult::Save
}

/// Apply token usage and frozen per-stream cost to state counters.
fn apply_token_usage(app_state: &mut State, usage: &TokenUsage, cost: &StreamCost) {
    // Set tick usage (this tick only)
    app_state.tick_cache_hit_tokens = usage.cache_hit;
    app_state.tick_cache_miss_tokens = usage.cache_miss;
    app_state.tick_output_tokens = usage.output;
    app_state.tick_uncached_input_tokens = usage.uncached_input;
    app_state.tick_cost_hit_usd = cost.hit;
    app_state.tick_cost_miss_usd = cost.miss;
    app_state.tick_cost_output_usd = cost.output;

    // Accumulate per-stream usage (reset at InputSubmit)
    app_state.stream_cache_hit_tokens = app_state.stream_cache_hit_tokens.saturating_add(usage.cache_hit);
    app_state.stream_cache_miss_tokens = app_state.stream_cache_miss_tokens.saturating_add(usage.cache_miss);
    app_state.stream_output_tokens = app_state.stream_output_tokens.saturating_add(usage.output);
    app_state.stream_uncached_input_tokens =
        app_state.stream_uncached_input_tokens.saturating_add(usage.uncached_input);
    app_state.stream_cost_hit_usd += cost.hit;
    app_state.stream_cost_miss_usd += cost.miss;
    app_state.stream_cost_output_usd += cost.output;

    // Accumulate total usage
    app_state.cache_hit_tokens = app_state.cache_hit_tokens.saturating_add(usage.cache_hit);
    app_state.cache_miss_tokens = app_state.cache_miss_tokens.saturating_add(usage.cache_miss);
    app_state.total_output_tokens = app_state.total_output_tokens.saturating_add(usage.output);
    app_state.uncached_input_tokens = app_state.uncached_input_tokens.saturating_add(usage.uncached_input);
    app_state.cost_hit_usd += cost.hit;
    app_state.cost_miss_usd += cost.miss;
    app_state.cost_output_usd += cost.output;
}

/// Handle `StreamError` action — clean up streaming state, log error.
pub(crate) fn handle_stream_error(state: &mut State, error: &str) -> ActionResult {
    const INLINE_LIMIT: usize = 1000;

    state.flags.stream.phase.transition(StreamPhase::Idle);

    // Remove estimated tokens on error from Conversation context
    if let Some(ctx) = state.context.iter_mut().find(|c| c.context_type.as_str() == Kind::CONVERSATION) {
        ctx.token_count = ctx.token_count.saturating_sub(state.streaming_estimated_tokens);
    }
    state.streaming_estimated_tokens = 0;

    // Log error to file
    let error_file = log_error(error);

    // Truncate error for inline display (~1000 chars, UTF-8 safe)
    let preview = if error.len() <= INLINE_LIMIT {
        error.to_owned()
    } else {
        let boundary =
            error.char_indices().map(|(i, _)| i).take_while(|&i| i <= INLINE_LIMIT).last().unwrap_or(INLINE_LIMIT);
        format!("{}… (truncated)", error.get(..boundary).unwrap_or(error))
    };

    if let Some(msg) = state.messages.last_mut()
        && msg.role == "assistant"
    {
        msg.content = format!("[Error occurred. Full details in {error_file}]\n\n{preview}");
        let id = msg.id.clone();
        return ActionResult::SaveMessage(id);
    }
    ActionResult::Save
}
