//! Dynamic Caddyfile generation + reload — the private-CA TLS plane (M3).
//!
//! The appliance terminates **all** TLS in Caddy using its built-in CA
//! (`tls internal`), never public ACME (the box is a "rien sur le web" LAN
//! appliance, architecture memory `local-tls-onboarding`). The orchestrator owns
//! the Caddyfile: it renders the config from the current provisioning state +
//! identity and asks Caddy to reload, so the cockpit only ever appears on
//! `:443` once the box is provisioned.
//!
//! Port map (Caddy front → orchestrator upstream), design §13.4 (no maintenance
//! plane — the cockpit brings itself up over cleartext at day-0):
//! * `:80`  → `127.0.0.1:7878` — the cockpit itself, served in **cleartext**
//!   while **un**provisioned so the day-0 flow (login → set identity) works
//!   before any cert exists.
//! * `:443` → `127.0.0.1:7878` — product cockpit over private-CA TLS, served
//!   **only** when provisioned.
//! * `:80`  → 308 redirect to `:443` **once provisioned** — no cleartext app
//!   surface after day-0.
//!
//! Reload is **best-effort and env-gated**: with no `CP_CADDYFILE` set (local
//! dev, tests) the whole step is skipped, so the orchestrator runs fine without
//! Caddy. With it set, the render is written atomically and `caddy reload` is
//! invoked; a failed reload **rolls back** to the previous Caddyfile so a bad
//! identity can never wedge TLS.

use std::ffi::OsStr;
use std::path::Path;

use super::identity::Identity;
use super::state::write_atomic;

/// Orchestrator product (cockpit + SPA) HTTP upstream Caddy proxies to.
const PRODUCT_UPSTREAM: &str = "127.0.0.1:7878";

/// Render a complete Caddyfile for the given state (design §13.4 — no separate
/// maintenance plane).
///
/// `subjects` is the list of names/IPs the certs should cover (e.g.
/// `["192.168.1.116", "pilot.acme.corp"]`); the first is typically the box IP.
/// When empty (identity not set and IP undetectable) the blocks fall back to
/// port-only / scheme-only site addresses so Caddy still serves something.
///
/// Two states:
/// * **Un**provisioned (day-0, or no subjects yet) → the cockpit is served on
///   **`:80` in cleartext**, so an IT operator can log in and set the network
///   identity before any cert (and thus `:443`) can exist.
/// * **Provisioned** *and* subjects known → the cockpit is served on `:443` over
///   private-CA TLS, and `:80` becomes a **308 redirect to https** — no cleartext
///   app surface after day-0.
///
/// Every block pins `bind 0.0.0.0 ::` so Caddy listens on all interfaces
/// regardless of whether a site address is an IP or a hostname — otherwise an IP
/// site address would bind that one IP while a hostname address binds all,
/// producing conflicting listeners on the same port, and a DHCP IP change would
/// wedge Caddy. IPv6 literals are bracketed so `[fd00::1]:443` parses.
#[must_use]
pub(crate) fn render_caddyfile(provisioned: bool, subjects: &[String]) -> String {
    let mut out = String::new();
    out.push_str("# Generated by the Context Pilot orchestrator — do not edit by hand.\n");
    out.push_str("# Private-CA TLS (tls internal); regenerated on identity changes.\n");
    out.push_str("{\n\t# LAN appliance: never reach out to public ACME.\n\tauto_https disable_redirects\n}\n\n");

    // The cockpit needs real subjects for a trustworthy leaf; with none known we
    // keep `:443` gated even if the provisioned flag is set and fall back to the
    // cleartext `:80` cockpit (defence against a removed identity file).
    if provisioned && !subjects.is_empty() {
        out.push_str("# Product cockpit — private-CA TLS, served once provisioned.\n");
        out.push_str(&site_line(subjects, "https", None));
        out.push_str(" {\n\tbind 0.0.0.0 ::\n\ttls internal\n\treverse_proxy ");
        out.push_str(PRODUCT_UPSTREAM);
        out.push_str("\n}\n\n");

        out.push_str("# Plain HTTP → HTTPS (only once provisioned — no app on :80).\n");
        out.push_str(&site_line(subjects, "http", Some(80)));
        out.push_str(" {\n\tbind 0.0.0.0 ::\n\tredir https://{host}{uri} 308\n}\n");
    } else {
        // Day-0: no cert yet. Serve the cockpit itself over cleartext `:80` so the
        // operator can log in and set the network identity (which provisions the
        // box and brings `:443` up).
        out.push_str("# Day-0 cockpit — cleartext :80 until the box is provisioned.\n");
        out.push_str(&site_line(subjects, "http", Some(80)));
        out.push_str(" {\n\tbind 0.0.0.0 ::\n\treverse_proxy ");
        out.push_str(PRODUCT_UPSTREAM);
        out.push_str("\n}\n");
    }

    out
}

/// Build a `<scheme>://…` site-address list for `subjects` at an optional port,
/// bracketing IPv6 literals. Falls back to a port-only / scheme-only address
/// when there are no subjects.
fn site_line(subjects: &[String], scheme: &str, port: Option<u16>) -> String {
    if subjects.is_empty() {
        return port.map_or_else(|| format!("{scheme}://"), |p| format!(":{p}"));
    }
    subjects
        .iter()
        .map(|s| {
            let host = bracketed(s);
            match port {
                Some(p) => format!("{scheme}://{host}:{p}"),
                None => format!("{scheme}://{host}"),
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Bracket an IPv6 literal (`fd00::1` → `[fd00::1]`) so it is a valid host in a
/// `scheme://host:port` address; pass hostnames and IPv4 through unchanged.
fn bracketed(subject: &str) -> String {
    if subject.parse::<std::net::Ipv6Addr>().is_ok() { format!("[{subject}]") } else { subject.to_owned() }
}

/// Compute the cert subjects for the current identity: `[ip, name]` when an
/// identity is set, otherwise the auto-detected box IP (so the cockpit is
/// reachable by IP before the operator names the box), or empty if even that
/// is undetectable.
#[must_use]
pub(crate) fn subjects_for(identity: Option<&Identity>) -> Vec<String> {
    match identity {
        Some(id) => {
            let mut v = vec![id.ip.clone()];
            if !id.name.trim().is_empty() {
                v.push(id.name.clone());
            }
            v
        }
        None => detect_host_ip().into_iter().collect(),
    }
}

/// Best-effort primary LAN IP detection: open a UDP socket "connected" to an
/// off-link address and read back the local address the kernel would route from.
/// No packet is sent (UDP connect only sets the route), so this works offline.
fn detect_host_ip() -> Option<String> {
    let sock = std::net::UdpSocket::bind("0.0.0.0:0").ok()?;
    sock.connect("8.8.8.8:53").ok()?;
    sock.local_addr().ok().map(|addr| addr.ip().to_string())
}

/// Serializes the render→write→reload critical section across the
/// thread-per-request server, so two concurrent IT calls that set the identity
/// can't interleave writes/rollbacks on the same Caddyfile. A
/// dedicated lock, never the backend `Mutex`, so it's safe to hold across the
/// `caddy reload` subprocess.
static CADDY_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

/// Render the Caddyfile for the current state and write it **without reloading**.
///
/// Used at boot (Caddy isn't up yet, so its admin API is unreachable; Caddy
/// loads the freshly-written file on its own start a moment later). Returns
/// `Ok(true)` when the file was written, `Ok(false)` when skipped (no
/// `CP_CADDYFILE` — local dev / tests).
///
/// # Errors
///
/// Returns a message if the Caddyfile cannot be written.
pub(crate) fn write_config(provisioned: bool, identity: Option<&Identity>) -> Result<bool, String> {
    let Some(caddyfile) = std::env::var_os("CP_CADDYFILE") else {
        return Ok(false);
    };
    let _guard = CADDY_LOCK.lock();
    let content = render_caddyfile(provisioned, &subjects_for(identity));
    write_atomic(Path::new(&caddyfile), content.as_bytes()).map_err(|e| format!("write Caddyfile: {e}"))?;
    Ok(true)
}

/// Render the Caddyfile for the current state, write it, and reload a running
/// Caddy. Used by the IT identity handler (Caddy is already up).
///
/// Returns `Ok(true)` when Caddy was reloaded, `Ok(false)` when skipped (no
/// `CP_CADDYFILE`, or no `CP_CADDY_BIN` to reload with). On a reload failure the
/// previous Caddyfile is restored and re-applied, and an `Err` is returned, so a
/// bad identity never wedges TLS.
///
/// # Errors
///
/// Returns a message if the Caddyfile cannot be written or `caddy reload` fails.
pub(crate) fn regenerate(provisioned: bool, identity: Option<&Identity>) -> Result<bool, String> {
    let Some(caddyfile) = std::env::var_os("CP_CADDYFILE") else {
        return Ok(false); // no Caddy in this environment — skip cleanly.
    };
    let path = Path::new(&caddyfile);
    let _guard = CADDY_LOCK.lock();
    let content = render_caddyfile(provisioned, &subjects_for(identity));
    let backup = std::fs::read(path).ok();

    write_atomic(path, content.as_bytes()).map_err(|e| format!("write Caddyfile: {e}"))?;

    let Some(bin) = std::env::var_os("CP_CADDY_BIN") else {
        return Ok(false); // wrote the file but have no caddy binary to reload (dev).
    };
    match reload(&bin, path) {
        Ok(()) => Ok(true),
        Err(e) => {
            if let Some(prev) = backup {
                let _restored = write_atomic(path, &prev);
                let _reapplied = reload(&bin, path);
            }
            Err(format!("caddy reload failed (rolled back): {e}"))
        }
    }
}

/// Invoke `caddy reload --config <path> --adapter caddyfile`.
fn reload(bin: &OsStr, path: &Path) -> Result<(), String> {
    let output = std::process::Command::new(bin)
        .arg("reload")
        .arg("--config")
        .arg(path)
        .arg("--adapter")
        .arg("caddyfile")
        .output()
        .map_err(|e| format!("spawn caddy: {e}"))?;
    if output.status.success() { Ok(()) } else { Err(String::from_utf8_lossy(&output.stderr).trim().to_owned()) }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn subjects() -> Vec<String> {
        vec!["192.168.1.116".to_owned(), "pilot.acme.corp".to_owned()]
    }

    #[test]
    fn unprovisioned_render_serves_cockpit_over_cleartext_80() {
        let cfg = render_caddyfile(false, &subjects());
        // Day-0: the cockpit is served on :80 cleartext, proxying the product
        // upstream — no cert, no :443, no redirect.
        assert!(cfg.contains(PRODUCT_UPSTREAM), "cockpit is served on day-0");
        assert!(cfg.contains("http://192.168.1.116:80"), "cockpit on cleartext :80 by IP");
        assert!(!cfg.contains("https://"), "no https site until provisioned");
        assert!(!cfg.contains("redir https"), "no :80→:443 redirect when unprovisioned");
        // The removed maintenance plane leaves no trace.
        assert!(!cfg.contains("9090"), "no maintenance plane upstream/port");
    }

    #[test]
    fn provisioned_render_serves_cockpit_on_443_and_redirects_80() {
        let cfg = render_caddyfile(true, &subjects());
        assert!(cfg.contains(PRODUCT_UPSTREAM), "cockpit upstream present once provisioned");
        assert!(cfg.contains("tls internal"), "cockpit uses the private CA once provisioned");
        assert!(cfg.contains("https://pilot.acme.corp"), "name is a cert subject");
        assert!(cfg.contains("https://192.168.1.116"), "ip is a cert subject");
        assert!(cfg.contains("redir https://{host}{uri} 308"), ":80 → :443 redirect present");
        // The cockpit is no longer reverse-proxied on :80 once provisioned — only
        // the redirect block references :80.
        assert!(!cfg.contains("9090"), "no maintenance plane upstream/port");
    }

    #[test]
    fn empty_subjects_fall_back_to_cleartext_80_cockpit() {
        // No subjects → treated as day-0: cockpit on a port-only :80 site.
        let cfg = render_caddyfile(true, &[]);
        assert!(cfg.contains(":80"), "cockpit falls back to a port-only :80 site");
        assert!(cfg.contains(PRODUCT_UPSTREAM), "cockpit is still served");
        assert!(!cfg.contains("https://"), "no https site without subjects for a trustworthy leaf");
    }

    #[test]
    fn subjects_for_orders_ip_then_name() {
        let id = Identity { name: "pilot.acme.corp".to_owned(), ip: "10.0.0.9".to_owned() };
        assert_eq!(subjects_for(Some(&id)), vec!["10.0.0.9".to_owned(), "pilot.acme.corp".to_owned()]);
        // A blank name is dropped.
        let id2 = Identity { name: "  ".to_owned(), ip: "10.0.0.9".to_owned() };
        assert_eq!(subjects_for(Some(&id2)), vec!["10.0.0.9".to_owned()]);
    }

    #[test]
    fn every_block_binds_all_interfaces() {
        // `bind 0.0.0.0 ::` on every block avoids the IP-vs-hostname conflicting
        // listener problem and survives a DHCP IP change.
        let provisioned = render_caddyfile(true, &subjects());
        assert_eq!(provisioned.matches("bind 0.0.0.0 ::").count(), 2, "cockpit + redirect bind all interfaces");
        // Day-0 renders a single cleartext cockpit block.
        let day0 = render_caddyfile(false, &subjects());
        assert_eq!(day0.matches("bind 0.0.0.0 ::").count(), 1, "the day-0 :80 cockpit binds all interfaces");
    }

    #[test]
    fn ipv6_subjects_are_bracketed() {
        let cfg = render_caddyfile(true, &["fd00::1".to_owned()]);
        assert!(cfg.contains("https://[fd00::1]"), "ipv6 cockpit address is bracketed");
        assert!(cfg.contains("http://[fd00::1]:80"), "ipv6 redirect address is bracketed");
        // IPv4 is never bracketed.
        let v4 = render_caddyfile(false, &["10.0.0.9".to_owned()]);
        assert!(!v4.contains('['), "ipv4 is not bracketed");
    }

    #[test]
    fn provisioned_but_no_subjects_keeps_443_gated() {
        // Defence against a removed identity file: provisioned flag set but no
        // subjects → no `:443`/TLS block; fall back to the cleartext `:80` cockpit
        // rather than exposing an untrusted leaf.
        let cfg = render_caddyfile(true, &[]);
        assert!(!cfg.contains("https://"), "no https cockpit without subjects");
        assert!(!cfg.contains("redir https"), "no redirect without a :443 to redirect to");
        assert!(cfg.contains(PRODUCT_UPSTREAM) && cfg.contains(":80"), "cockpit stays reachable on :80");
    }

    #[test]
    fn regenerate_is_skipped_without_caddyfile_env() {
        // No CP_CADDYFILE in the test environment → clean skip, never errors.
        let id = Identity { name: "n".to_owned(), ip: "10.0.0.9".to_owned() };
        assert_eq!(regenerate(true, Some(&id)), Ok(false));
    }
}
