//! Dynamic Caddyfile generation + reload — the private-CA TLS plane (M3).
//!
//! The appliance terminates **all** TLS in Caddy using its built-in CA
//! (`tls internal`), never public ACME (the box is a "rien sur le web" LAN
//! appliance, architecture memory `local-tls-onboarding`). The orchestrator owns
//! the Caddyfile: it renders the config from the current provisioning state +
//! identity and asks Caddy to reload, so the cockpit only ever appears on
//! `:443` once the box is provisioned.
//!
//! Port map (Caddy front → orchestrator upstream), design §13.4 (no maintenance
//! plane — the cockpit brings itself up over cleartext at day-0):
//! * `:80`  → `127.0.0.1:7878` — the cockpit itself, served in **cleartext**
//!   while **un**provisioned so the day-0 flow (login → set identity) works
//!   before any cert exists. Matched on **any host**: the first connection to a
//!   freshly-installed box arrives on its fleet ULA (deterministic, derived from
//!   the hardware serial) precisely because nobody knows its DHCP IPv4 yet.
//! * `:443` → `127.0.0.1:7878` — product cockpit over private-CA TLS, served
//!   **only** when provisioned.
//! * `:80`  → 308 redirect to `:443` **once provisioned** — no cleartext app
//!   surface after day-0.
//!
//! Caddy is the **only** LAN-facing surface: the orchestrator itself binds
//! loopback (`CP_ORCH_BIND`, default `127.0.0.1` — see
//! [`crate::runtime::Config`]), so the redirect above cannot be sidestepped by
//! talking to `:7878` directly, and the auth model keeps its assumption of an
//! encrypted transport.
//!
//! Reload is **best-effort and env-gated**: with no `CP_CADDYFILE` set (local
//! dev, tests) the whole step is skipped, so the orchestrator runs fine without
//! Caddy. With it set, the render is written atomically and `caddy reload` is
//! invoked; a failed reload **rolls back** to the previous Caddyfile so a bad
//! identity can never wedge TLS.

use std::ffi::OsStr;
use std::path::Path;

use super::identity::Identity;
use super::state::write_atomic;

/// Orchestrator product (cockpit + SPA) HTTP upstream Caddy proxies to.
const PRODUCT_UPSTREAM: &str = "127.0.0.1:7878";

/// Render a complete Caddyfile for the given state (design §13.4 — no separate
/// maintenance plane).
///
/// `subjects` is the list of names/IPs the certs should cover (e.g.
/// `["192.168.1.116", "pilot.acme.corp", "fd59:ec78:2da4:1:7681:f2a2:27e0:f10d"]`):
/// the operator-chosen IP and name, plus every fleet ULA the box carries. When
/// empty (identity not set and IP undetectable) the blocks fall back to port-only
/// / scheme-only site addresses so Caddy still serves something.
///
/// Two states:
/// * **Un**provisioned (day-0) → the cockpit is served on **`:80` in cleartext**,
///   on a **port-only** site address that matches any host, so an IT operator can
///   log in over whichever address they have — in practice the ULA, since the DHCP
///   IPv4 is still unknown — and set the network identity before any cert (and
///   thus `:443`) can exist. `subjects` is ignored in this state.
/// * **Provisioned** *and* subjects known → the cockpit is served on `:443` over
///   private-CA TLS, and `:80` becomes a **308 redirect to https** — no cleartext
///   app surface after day-0.
///
/// Every block pins `bind 0.0.0.0 ::` so Caddy listens on all interfaces
/// regardless of whether a site address is an IP or a hostname — otherwise an IP
/// site address would bind that one IP while a hostname address binds all,
/// producing conflicting listeners on the same port, and a DHCP IP change would
/// wedge Caddy. IPv6 literals are bracketed so `[fd00::1]:443` parses.
#[must_use]
pub(crate) fn render_caddyfile(provisioned: bool, subjects: &[String]) -> String {
    let mut out = String::new();
    out.push_str("# Generated by the Context Pilot orchestrator — do not edit by hand.\n");
    out.push_str("# Private-CA TLS (tls internal); regenerated on identity changes.\n");
    out.push_str("{\n\t# LAN appliance: never reach out to public ACME.\n\tauto_https disable_redirects\n}\n\n");

    // The cockpit needs real subjects for a trustworthy leaf; with none known we
    // keep `:443` gated even if the provisioned flag is set and fall back to the
    // cleartext `:80` cockpit (defence against a removed identity file).
    if provisioned && !subjects.is_empty() {
        out.push_str("# Product cockpit — private-CA TLS, served once provisioned.\n");
        out.push_str(&site_line(subjects, "https", None));
        out.push_str(" {\n\tbind 0.0.0.0 ::\n\ttls internal\n\treverse_proxy ");
        out.push_str(PRODUCT_UPSTREAM);
        out.push_str("\n}\n\n");

        out.push_str("# Plain HTTP → HTTPS (only once provisioned — no app on :80).\n");
        out.push_str(&site_line(subjects, "http", Some(80)));
        out.push_str(" {\n\tbind 0.0.0.0 ::\n\tredir https://{host}{uri} 308\n}\n");
    } else {
        // Day-0: no cert yet. Serve the cockpit itself over cleartext `:80` so the
        // operator can log in and set the network identity (which provisions the
        // box and brings `:443` up).
        //
        // Deliberately a PORT-ONLY site address, ignoring `subjects`: at day-0 the
        // box's IPv4 is whatever DHCP happened to hand out and nobody knows it yet,
        // so the first connection comes in on the address that IS known in advance —
        // the fleet ULA, derived from the hardware serial. Matching on a detected
        // IPv4 host would answer that request with an empty 200 (Caddy matched no
        // site), which is exactly the trap this avoids. There is no cert to protect
        // and no vhost to multiplex here, so host matching buys nothing; it starts
        // once the operator has pinned an identity.
        out.push_str("# Day-0 cockpit — cleartext :80, ANY host (the ULA is the way in).\n");
        out.push_str(&site_line(&[], "http", Some(80)));
        out.push_str(" {\n\tbind 0.0.0.0 ::\n\treverse_proxy ");
        out.push_str(PRODUCT_UPSTREAM);
        out.push_str("\n}\n");
    }

    out
}

/// Build a `<scheme>://…` site-address list for `subjects` at an optional port,
/// bracketing IPv6 literals. Falls back to a port-only / scheme-only address
/// when there are no subjects.
fn site_line(subjects: &[String], scheme: &str, port: Option<u16>) -> String {
    if subjects.is_empty() {
        return port.map_or_else(|| format!("{scheme}://"), |p| format!(":{p}"));
    }
    subjects
        .iter()
        .map(|s| {
            let host = bracketed(s);
            match port {
                Some(p) => format!("{scheme}://{host}:{p}"),
                None => format!("{scheme}://{host}"),
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Bracket an IPv6 literal (`fd00::1` → `[fd00::1]`) so it is a valid host in a
/// `scheme://host:port` address; pass hostnames and IPv4 through unchanged.
fn bracketed(subject: &str) -> String {
    if subject.parse::<std::net::Ipv6Addr>().is_ok() { format!("[{subject}]") } else { subject.to_owned() }
}

/// Compute the cert subjects for the current identity: `[ip, name]` when an
/// identity is set, otherwise the auto-detected box IP (so the cockpit is
/// reachable by IP before the operator names the box), plus **every fleet ULA the
/// box carries**, plus `extra`. Empty when nothing is known at all.
///
/// `extra` is how a feature that creates a NEW address on the box gets a cert
/// for it. Today that is the Wi-Fi AP's `10.42.0.1`: Caddy listens on the
/// wildcard `*:443` but the generated file enumerates explicit site addresses,
/// so without this an AP client gets a TLS `internal error` while plain HTTP
/// answers `200` — measured on hardware, not deduced.
///
/// The ULA is appended, never operator-entered: `Identity` holds a single `ip`,
/// and that one belongs to the CLIENT (the address their staff and their DNS will
/// use). Putting the ULA there would take the cockpit away from them. Conversely
/// the ULA is a vendor constant the box can derive on its own, so it belongs on
/// the auto-detected side — and it is the only subject that never changes, which
/// makes it the recovery path when the pinned DHCP IPv4 drifts.
///
/// Appended only to a NON-empty base, so the "identity file removed" defence in
/// `render_caddyfile` still fires: with no operator identity and no detectable
/// IPv4 we return empty and the caller falls back to the cleartext `:80` cockpit,
/// rather than standing up a `:443` that only we could reach.
#[must_use]
pub(crate) fn subjects_for(identity: Option<&Identity>, extra: &[String]) -> Vec<String> {
    let mut detected = detect_ulas();
    detected.extend_from_slice(extra);
    subjects_with(identity, detect_host_ip().as_deref(), &detected)
}

/// Pure composition half of [`subjects_for`] — every probe is passed in rather
/// than performed here, so the ordering and fallback rules are fully determined by
/// the arguments and testable without depending on whatever addresses the machine
/// running the tests happens to carry.
fn subjects_with(identity: Option<&Identity>, detected_ip: Option<&str>, ulas: &[String]) -> Vec<String> {
    let mut v = match identity {
        Some(id) => {
            let mut v = vec![id.ip.clone()];
            if !id.name.trim().is_empty() {
                v.push(id.name.clone());
            }
            v
        }
        None => detected_ip.map(ToOwned::to_owned).into_iter().collect::<Vec<_>>(),
    };
    if v.is_empty() {
        return v;
    }
    for ula in ulas {
        if !v.contains(ula) {
            v.push(ula.clone());
        }
    }
    v
}

/// Best-effort primary LAN IP detection: open a UDP socket "connected" to an
/// off-link address and read back the local address the kernel would route from.
/// No packet is sent (UDP connect only sets the route), so this works offline.
/// `pub(crate)` so the identity endpoint can report the same value the renderer
/// would use as a subject — the wizard must show the operator exactly the address
/// the box would put in the cert, not an independently-guessed one.
pub(crate) fn detect_host_ip() -> Option<String> {
    let sock = std::net::UdpSocket::bind("0.0.0.0:0").ok()?;
    sock.connect("8.8.8.8:53").ok()?;
    sock.local_addr().ok().map(|addr| addr.ip().to_string())
}

/// Every ULA (RFC 4193, `fd00::/8`) configured on a non-loopback interface, in
/// canonical form, sorted and de-duplicated.
///
/// Read from `/proc/net/if_inet6` rather than an interface-enumeration crate: the
/// std library cannot list interfaces, and the UDP-connect trick used for IPv4
/// would need the prefix up front. Absent file (non-Linux dev machine) → empty.
///
/// Sorted so the render is byte-stable across boots: an unstable subject order
/// would rewrite the Caddyfile and re-issue the leaf for nothing.
pub(crate) fn detect_ulas() -> Vec<String> {
    std::fs::read_to_string("/proc/net/if_inet6").map(|t| parse_ulas(&t)).unwrap_or_default()
}

/// Pure half of [`detect_ulas`] — parses `/proc/net/if_inet6` content.
///
/// Format is `<32 hex chars, no colons> <ifindex> <prefixlen> <scope> <flags> <dev>`.
/// We keep global-scope (`00`) addresses in `fd00::/8` on a real device, and
/// canonicalise through `Ipv6Addr` so what we emit matches what `ip -6 addr`
/// prints back (RFC 5952 zero-run compression included).
fn parse_ulas(text: &str) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for line in text.lines() {
        let mut f = line.split_whitespace();
        let (Some(hex), Some(_idx), Some(_plen), Some(scope), Some(_flags), Some(dev)) =
            (f.next(), f.next(), f.next(), f.next(), f.next(), f.next())
        else {
            continue;
        };
        // Global scope only: link-local (fe80, scope 20) and host-scope addresses
        // are not usable as cert subjects or site addresses.
        if hex.len() != 32 || scope != "00" || dev == "lo" {
            continue;
        }
        // `fd` == fc00::/7 with the L bit set: the locally-assigned half, i.e. the
        // only ULA form that actually exists in practice.
        if !hex.starts_with("fd") {
            continue;
        }
        let grouped =
            hex.as_bytes().chunks(4).map(|c| String::from_utf8_lossy(c).into_owned()).collect::<Vec<_>>().join(":");
        if let Ok(addr) = grouped.parse::<std::net::Ipv6Addr>() {
            let canonical = addr.to_string();
            if !out.contains(&canonical) {
                out.push(canonical);
            }
        }
    }
    out.sort();
    out
}

/// Serializes the render→write→reload critical section across the
/// thread-per-request server, so two concurrent IT calls that set the identity
/// can't interleave writes/rollbacks on the same Caddyfile. A
/// dedicated lock, never the backend `Mutex`, so it's safe to hold across the
/// `caddy reload` subprocess.
static CADDY_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

/// Render the Caddyfile for the current state and write it **without reloading**.
///
/// Used at boot (Caddy isn't up yet, so its admin API is unreachable; Caddy
/// loads the freshly-written file on its own start a moment later). Returns
/// `Ok(true)` when the file was written, `Ok(false)` when skipped (no
/// `CP_CADDYFILE` — local dev / tests).
///
/// # Errors
///
/// Returns a message if the Caddyfile cannot be written.
pub(crate) fn write_config(provisioned: bool, identity: Option<&Identity>, extra: &[String]) -> Result<bool, String> {
    let Some(caddyfile) = std::env::var_os("CP_CADDYFILE") else {
        return Ok(false);
    };
    let _guard = CADDY_LOCK.lock();
    let content = render_caddyfile(provisioned, &subjects_for(identity, extra));
    write_atomic(Path::new(&caddyfile), content.as_bytes()).map_err(|e| format!("write Caddyfile: {e}"))?;
    Ok(true)
}

/// Render the Caddyfile for the current state, write it, and reload a running
/// Caddy. Used by the IT identity handler (Caddy is already up).
///
/// Returns `Ok(true)` when Caddy was reloaded, `Ok(false)` when skipped (no
/// `CP_CADDYFILE`, or no `CP_CADDY_BIN` to reload with). On a reload failure the
/// previous Caddyfile is restored and re-applied, and an `Err` is returned, so a
/// bad identity never wedges TLS.
///
/// # Errors
///
/// Returns a message if the Caddyfile cannot be written or `caddy reload` fails.
pub(crate) fn regenerate(provisioned: bool, identity: Option<&Identity>, extra: &[String]) -> Result<bool, String> {
    let Some(caddyfile) = std::env::var_os("CP_CADDYFILE") else {
        return Ok(false); // no Caddy in this environment — skip cleanly.
    };
    let path = Path::new(&caddyfile);
    let _guard = CADDY_LOCK.lock();
    let content = render_caddyfile(provisioned, &subjects_for(identity, extra));
    let backup = std::fs::read(path).ok();

    write_atomic(path, content.as_bytes()).map_err(|e| format!("write Caddyfile: {e}"))?;

    let Some(bin) = std::env::var_os("CP_CADDY_BIN") else {
        return Ok(false); // wrote the file but have no caddy binary to reload (dev).
    };
    match reload(&bin, path) {
        Ok(()) => Ok(true),
        Err(e) => {
            if let Some(prev) = backup {
                let _restored = write_atomic(path, &prev);
                let _reapplied = reload(&bin, path);
            }
            Err(format!("caddy reload failed (rolled back): {e}"))
        }
    }
}

/// Invoke `caddy reload --config <path> --adapter caddyfile`.
fn reload(bin: &OsStr, path: &Path) -> Result<(), String> {
    let output = std::process::Command::new(bin)
        .arg("reload")
        .arg("--config")
        .arg(path)
        .arg("--adapter")
        .arg("caddyfile")
        .output()
        .map_err(|e| format!("spawn caddy: {e}"))?;
    if output.status.success() { Ok(()) } else { Err(String::from_utf8_lossy(&output.stderr).trim().to_owned()) }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn subjects() -> Vec<String> {
        vec!["192.168.1.116".to_owned(), "pilot.acme.corp".to_owned()]
    }

    #[test]
    fn unprovisioned_render_serves_cockpit_over_cleartext_80() {
        let cfg = render_caddyfile(false, &subjects());
        // Day-0: the cockpit is served on :80 cleartext, proxying the product
        // upstream — no cert, no :443, no redirect.
        assert!(cfg.contains(PRODUCT_UPSTREAM), "cockpit is served on day-0");
        assert!(!cfg.contains("https://"), "no https site until provisioned");
        assert!(!cfg.contains("redir https"), "no :80→:443 redirect when unprovisioned");
        // The removed maintenance plane leaves no trace.
        assert!(!cfg.contains("9090"), "no maintenance plane upstream/port");
    }

    #[test]
    fn unprovisioned_render_matches_any_host_so_the_ula_gets_in() {
        // The whole point of day-0: the operator's FIRST connection arrives on the
        // fleet ULA, because the DHCP IPv4 is not known to anyone yet. A host-scoped
        // site address would answer that request with an empty 200 (no site matched),
        // so the day-0 block must be port-only — subjects are deliberately ignored.
        let cfg = render_caddyfile(false, &subjects());
        assert!(cfg.contains("\n:80 {"), "day-0 uses a port-only :80 site address");
        assert!(!cfg.contains("192.168.1.116"), "day-0 does not scope to the detected IPv4");
        assert!(!cfg.contains("pilot.acme.corp"), "day-0 does not scope to the name either");
    }

    #[test]
    fn provisioned_render_serves_cockpit_on_443_and_redirects_80() {
        let cfg = render_caddyfile(true, &subjects());
        assert!(cfg.contains(PRODUCT_UPSTREAM), "cockpit upstream present once provisioned");
        assert!(cfg.contains("tls internal"), "cockpit uses the private CA once provisioned");
        assert!(cfg.contains("https://pilot.acme.corp"), "name is a cert subject");
        assert!(cfg.contains("https://192.168.1.116"), "ip is a cert subject");
        assert!(cfg.contains("redir https://{host}{uri} 308"), ":80 → :443 redirect present");
        // The cockpit is no longer reverse-proxied on :80 once provisioned — only
        // the redirect block references :80.
        assert!(!cfg.contains("9090"), "no maintenance plane upstream/port");
    }

    #[test]
    fn empty_subjects_fall_back_to_cleartext_80_cockpit() {
        // No subjects → treated as day-0: cockpit on a port-only :80 site.
        let cfg = render_caddyfile(true, &[]);
        assert!(cfg.contains(":80"), "cockpit falls back to a port-only :80 site");
        assert!(cfg.contains(PRODUCT_UPSTREAM), "cockpit is still served");
        assert!(!cfg.contains("https://"), "no https site without subjects for a trustworthy leaf");
    }

    #[test]
    fn subjects_for_orders_ip_then_name() {
        // No ULAs passed in: the client's identity alone, in order. (Uses the pure
        // half so the result does not depend on the test machine's addresses.)
        let id = Identity { name: "pilot.acme.corp".to_owned(), ip: "10.0.0.9".to_owned() };
        assert_eq!(subjects_with(Some(&id), None, &[]), vec!["10.0.0.9".to_owned(), "pilot.acme.corp".to_owned()]);
        // A blank name is dropped.
        let id2 = Identity { name: "  ".to_owned(), ip: "10.0.0.9".to_owned() };
        assert_eq!(subjects_with(Some(&id2), None, &[]), vec!["10.0.0.9".to_owned()]);
    }

    #[test]
    fn ulas_are_appended_after_the_client_identity() {
        // The client's IP/name come first — they are the identity the client's staff
        // and DNS use. Our ULAs ride along so the cockpit is also reachable on the
        // one address that never changes.
        let id = Identity { name: "pilot.acme.corp".to_owned(), ip: "10.0.0.9".to_owned() };
        let port1 = "fd59:ec78:2da4:1:7681:f2a2:27e0:f10d".to_owned();
        let port2 = "fd59:ec78:2da4:2:7681:f2a2:27e0:f10d".to_owned();
        let ulas = vec![port1.clone(), port2.clone()];
        assert_eq!(
            subjects_with(Some(&id), None, &ulas),
            vec!["10.0.0.9".to_owned(), "pilot.acme.corp".to_owned(), port1.clone(), port2]
        );
        // An operator who typed the ULA into the IP field must not get it twice.
        let id_ula = Identity { name: String::new(), ip: port1.clone() };
        assert_eq!(subjects_with(Some(&id_ula), None, std::slice::from_ref(&port1)), vec![port1]);
    }

    #[test]
    fn no_identity_and_no_detectable_ip_stays_empty_even_with_ulas() {
        // Defence-in-depth: a removed identity file must fall back to the cleartext
        // :80 cockpit, NOT to a :443 that only we could reach. So a ULA never turns
        // an empty subject list into a non-empty one.
        assert!(subjects_with(None, None, &["fd00::1".to_owned()]).is_empty());
    }

    #[test]
    fn parse_ulas_keeps_global_fd00_only() {
        // Real `/proc/net/if_inet6` shape: 32 hex chars, ifindex, prefixlen, scope,
        // flags, device. Scope 00 = global, 20 = link-local.
        let text = "\
fd59ec782da400017681f2a227e0f10d 02 40 00 80     end0
fd59ec782da400027681f2a227e0f10d 03 40 00 80     end1
fe80000000000000402f19fffe8ff932 02 40 20 80     end0
2a01cb088f5d2200402f19fffe8ff932 02 40 00 80     end0
00000000000000000000000000000001 01 80 10 80       lo
fd00000000000000000000000000abcd 01 80 00 80       lo
";
        assert_eq!(
            parse_ulas(text),
            vec!["fd59:ec78:2da4:1:7681:f2a2:27e0:f10d".to_owned(), "fd59:ec78:2da4:2:7681:f2a2:27e0:f10d".to_owned()],
            "global fd00::/8 on real devices only — link-local, GUA and loopback dropped"
        );
    }

    #[test]
    fn parse_ulas_is_canonical_sorted_and_deduped() {
        // Emitted form must match what `ip -6 addr` prints back (RFC 5952), or the
        // Caddyfile would churn against the kernel's spelling of the same address.
        let text = "\
fd0000000000000000000000000000ff 03 40 00 80     end1
fd00000000000000000000000000000a 02 40 00 80     end0
fd00000000000000000000000000000a 04 40 00 80     end2
";
        assert_eq!(parse_ulas(text), vec!["fd00::a".to_owned(), "fd00::ff".to_owned()]);
    }

    #[test]
    fn parse_ulas_ignores_malformed_lines() {
        let text = "not a line\nfd59ec78 02 40 00 80 end0\n\nfd59ec782da400017681f2a227e0f10d 02 40 00 80 end0\n";
        assert_eq!(parse_ulas(text), vec!["fd59:ec78:2da4:1:7681:f2a2:27e0:f10d".to_owned()]);
    }

    #[test]
    fn every_block_binds_all_interfaces() {
        // `bind 0.0.0.0 ::` on every block avoids the IP-vs-hostname conflicting
        // listener problem and survives a DHCP IP change.
        let provisioned = render_caddyfile(true, &subjects());
        assert_eq!(provisioned.matches("bind 0.0.0.0 ::").count(), 2, "cockpit + redirect bind all interfaces");
        // Day-0 renders a single cleartext cockpit block.
        let day0 = render_caddyfile(false, &subjects());
        assert_eq!(day0.matches("bind 0.0.0.0 ::").count(), 1, "the day-0 :80 cockpit binds all interfaces");
    }

    #[test]
    fn ipv6_subjects_are_bracketed() {
        let cfg = render_caddyfile(true, &["fd00::1".to_owned()]);
        assert!(cfg.contains("https://[fd00::1]"), "ipv6 cockpit address is bracketed");
        assert!(cfg.contains("http://[fd00::1]:80"), "ipv6 redirect address is bracketed");
        // IPv4 is never bracketed. Rendered PROVISIONED on purpose: the day-0 block
        // is port-only now, so it would pass this trivially and prove nothing.
        let v4 = render_caddyfile(true, &["10.0.0.9".to_owned()]);
        assert!(!v4.contains('['), "ipv4 is not bracketed");
    }

    #[test]
    fn provisioned_but_no_subjects_keeps_443_gated() {
        // Defence against a removed identity file: provisioned flag set but no
        // subjects → no `:443`/TLS block; fall back to the cleartext `:80` cockpit
        // rather than exposing an untrusted leaf.
        let cfg = render_caddyfile(true, &[]);
        assert!(!cfg.contains("https://"), "no https cockpit without subjects");
        assert!(!cfg.contains("redir https"), "no redirect without a :443 to redirect to");
        assert!(cfg.contains(PRODUCT_UPSTREAM) && cfg.contains(":80"), "cockpit stays reachable on :80");
    }

    #[test]
    fn regenerate_is_skipped_without_caddyfile_env() {
        // No CP_CADDYFILE in the test environment → clean skip, never errors.
        let id = Identity { name: "n".to_owned(), ip: "10.0.0.9".to_owned() };
        assert_eq!(regenerate(true, Some(&id), &[]), Ok(false));
    }
}
