import js from "@eslint/js"
import globals from "globals"
import reactHooks from "eslint-plugin-react-hooks"
import reactRefresh from "eslint-plugin-react-refresh"
import eslintComments from "@eslint-community/eslint-plugin-eslint-comments"
import unicorn from "eslint-plugin-unicorn"
import eslintReact from "@eslint-react/eslint-plugin"
import jsxA11y from "eslint-plugin-jsx-a11y"
import tseslint from "typescript-eslint"
import { defineConfig, globalIgnores } from "eslint/config"
import type { Linter } from "eslint"

/**
 * Frontend ESLint flat config — the Rust-parity strict stack (branch `web-lint`).
 *
 * Built as a RATCHET: plugin groups are switched on one phase at a time, each
 * landing at `error` with its violations burned down before the next is added
 * (see the P0→P13 roadmap). This file starts at the pre-existing effective
 * ruleset (P0) and grows toward ~1,100–1,400 active rules.
 *
 * `src/lib/api/generated/**` is globally ignored: it is OpenAPI codegen output
 * (regenerated by CB3/CB5), not hand-written — the analog of not linting Rust's
 * generated bindings. It must never be hand-edited to satisfy a lint.
 */
export default defineConfig([
  // Build artifacts + machine-generated code are never linted. Playwright e2e
  // specs + their config are a separate surface (test-runner globals, their own
  // idioms); they get a dedicated lint profile in P8 (test tooling), not the
  // app's type-aware pass — ignore them here so `projectService` doesn't fault
  // on files absent from the app/node tsconfigs.
  globalIgnores(["dist", "src/lib/api/generated/**", "e2e/**", "playwright.config.ts"]),
  {
    files: ["**/*.{ts,tsx}"],
    // P3 — the clippy-semantic twin. `strictTypeChecked` (superset of
    // recommended + recommendedTypeChecked) adds the whole type-aware rule set
    // — the analogue of clippy's `all + pedantic + nursery` correctness lints —
    // and `stylisticTypeChecked` the type-informed stylistic pass. Both land at
    // `error`; the gate runs `--max-warnings 0`. Type-aware rules require a
    // TypeScript program, wired below via `parserOptions.projectService`.
    extends: [
      js.configs.recommended,
      tseslint.configs.strictTypeChecked,
      tseslint.configs.stylisticTypeChecked,
      reactRefresh.configs.vite,
      unicorn.configs.recommended,
      // ── P6 React stack ──────────────────────────────────────────────────
      // The frontend twin of clippy's React-domain correctness lints. Three
      // presets, each landing at `error`:
      //   • @eslint-react recommended-type-checked — the modern successor to
      //     eslint-plugin-react (component/JSX correctness: unstable defaults,
      //     unused/invalid props, context/effect misuse). Type-aware, so it
      //     rides the projectService program wired below.
      //   • react-hooks recommended-latest (v7) — the classic hooks pair PLUS
      //     the compiler-aware rules (set-state-in-effect/render, immutability,
      //     refs, purity, static-components). Replaces the P0 manual pinning;
      //     exhaustive-deps is bumped from its recommended `warn` to `error` in
      //     the rules block below (the P0→P6 deferral now comes due).
      //   • jsx-a11y recommended — accessibility (alt text, roles, labels).
      eslintReact.configs["recommended-type-checked"],
      // `.configs.flat` is the flat-config surface of eslint-plugin-react-hooks
      // v7 (the bare `.configs["recommended-latest"]` is the legacy eslintrc
      // form — an array-of-strings `plugins`, which flat config rejects). The
      // plugin types `.flat` as `any`, so cast it to an object with the SINGLE
      // named key we read — a named-property cast (not a `Record<string, …>`
      // index signature) so the access yields `Linter.Config` directly, without
      // the `| undefined` that `noUncheckedIndexedAccess` adds to index-signature
      // reads (and without a `!` assertion, banned here). This also clears the
      // type-aware `no-unsafe-member-access` / `no-unsafe-assignment` rules that
      // would otherwise flag reading a member off an `any` and spreading it in.
      (reactHooks.configs.flat as { "recommended-latest": Linter.Config })["recommended-latest"],
      // eslint-plugin-jsx-a11y ships no bundled types (its module is declared
      // ambiently in types.d.ts to satisfy the strict `tsc` program), so its
      // default export is `any`. Cast to an object with exactly the nested named
      // property we use — again a named-property shape, not an index signature,
      // so `.flatConfigs.recommended` is `Linter.Config` (no `| undefined`, no
      // `noPropertyAccessFromIndexSignature` violation) and the surrounding
      // `no-unsafe-*` rules stay clear.
      (jsxA11y as { flatConfigs: { recommended: Linter.Config } }).flatConfigs.recommended,
    ],
    plugins: {
      // react-hooks is now registered via its v7 `recommended-latest` flat
      // preset in `extends` above (P6) — the manual P0 pinning to the classic
      // rules-of-hooks + exhaustive-deps pair (and the `ESLint.Plugin` cast that
      // bridged the plugin's then-unmodelled `.configs.flat` typing gap) is
      // gone. The preset ships the compiler-aware rule set and the plugin key,
      // so registering it here again would throw "Cannot redefine plugin".
      //
      // P4 anti-cheat layer: the eslint-comments plugin powers the ban on
      // suppression directives (its `no-use` rule reports EVERY `eslint-disable`
      // / `eslint-enable` comment). This is the frontend twin of the Rust
      // `#[allow]`/`#[expect]` ban — lint suppression is forbidden inline; the
      // only legal escape is a config-level scoped override, registered and
      // justified in `.github/checks/allowed-eslint-exceptions.yaml`. Unlike
      // react-hooks above, this plugin's default export already satisfies
      // ESLint's `Plugin` type, so no cast is needed (one would be flagged
      // unnecessary by @typescript-eslint/no-unnecessary-type-assertion).
      "@eslint-community/eslint-comments": eslintComments,
    },
    languageOptions: {
      globals: globals.browser,
      // `projectService` gives every linted file its TypeScript program so the
      // type-aware rules can query types. Config files not in a source tsconfig
      // (eslint.config.ts, vite.config.ts) are covered by tsconfig.node.json's
      // `include`. `tsconfigRootDir` anchors project discovery to this folder.
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    // P4 anti-cheat: a stale `eslint-disable` that suppresses nothing is itself
    // an error (belt-and-suspenders alongside the outright no-use ban below).
    linterOptions: {
      reportUnusedDisableDirectives: "error",
    },
    rules: {
      // ── P4 anti-suppression layer (the crown jewel — Rust #[allow]-ban twin) ──
      // Inline lint suppression is FORBIDDEN. The only legal escape is a
      // config-level scoped override registered in
      // .github/checks/allowed-eslint-exceptions.yaml (hash-locked) — never an
      // inline comment. A grep-guard (check-frontend-suppressions.sh) enforces
      // the same ban CI-side, independent of ESLint's own config.
      //
      // no-use bans EVERY eslint-disable/eslint-enable directive comment (any
      // form: line, next-line, block, whole-file). no-unlimited-disable also
      // catches a bare `eslint-disable` with no rule list.
      "@eslint-community/eslint-comments/no-use": "error",
      "@eslint-community/eslint-comments/no-unlimited-disable": "error",
      // ban-ts-comment is already error via strictTypeChecked, but its default
      // still permits `@ts-expect-error` with a ≥10-char description. Harden it:
      // ALL four TS directive comments are forbidden outright, no description
      // escape hatch (the generated bindings that legitimately carry @ts-nocheck
      // are globally-ignored above, so this never touches them).
      "@typescript-eslint/ban-ts-comment": [
        "error",
        {
          "ts-expect-error": true,
          "ts-ignore": true,
          "ts-nocheck": true,
          "ts-check": true,
        },
      ],
      // Classic react-hooks pair (see the plugins note above).
      // ── P6: exhaustive-deps comes due ──────────────────────────────────
      // react-hooks/recommended-latest (extends) sets rules-of-hooks + the
      // compiler-aware rules at error, but leaves exhaustive-deps at its
      // recommended `warn`. The P0→P5 deferral of the 3 known warnings
      // (CreateCommandDialog, MarkdownEditor, Finder — intentional mount-once
      // effects) now comes due: bump it to `error` and restructure each site
      // (a ref-captured seed / stable callback), never an inline disable (P4).
      "react-hooks/exhaustive-deps": "error",
      // `cva()` variant tables and other module-level `const` exports sit
      // beside their component (the shadcn/vite idiom). They don't break Fast
      // Refresh, so permit them; hooks/functions co-exported with components
      // still error and get factored into sibling modules.
      "react-refresh/only-export-components": ["error", { allowConstantExport: true }],
      // ── Two type-aware rules carry a codebase-contract OPTION (the twin of a
      //    clippy.toml threshold — a calibration, NOT a suppression; the rule
      //    stays at `error`): ──
      //
      // JSX event handlers are overwhelmingly `onClick={() => setState(x)}` —
      // an arrow whose void return is deliberately discarded by the prop. The
      // default forbids that shorthand, which would force noisy `{ … }` braces
      // on ~240 handlers for zero safety gain. `ignoreArrowShorthand` permits
      // exactly that shape while STILL flagging a void expression used as a
      // value (`const x = doVoid()`, `return doVoid()`) — the genuinely
      // confusing cases.
      "@typescript-eslint/no-confusing-void-expression": ["error", { ignoreArrowShorthand: true }],
      // Interpolating a `number` into a template literal is unambiguous and
      // universal (`${count}`, `${size}px`). `allowNumber` (the conventional
      // setting) permits it; a possibly-`undefined`/object/boolean interpolation
      // still errors and gets a real fix (guard / `String(x)` / `?? fallback`).
      "@typescript-eslint/restrict-template-expressions": ["error", { allowNumber: true }],
      // Third calibration (same clippy.toml-threshold spirit — NOT a blanket
      // suppression; the rule stays at `error`). The rule's safety concern is a
      // `x || fallback` that silently swallows a VALID falsy value (a real `0`,
      // `""`, or `false` that carried meaning). That danger is real for
      // **numbers** — a legitimate `0` must not be replaced — so `number`
      // stays flagged (→ genuine `?? ` fixes). But for **strings** and
      // **booleans** every `||` site in this codebase is a deliberate
      // truthy-or-fallback idiom where an empty string / `false` is *meant* to
      // take the fallback (display-name chains `name || ip || ""`, path-segment
      // fallbacks `split("/").pop() || path` where a trailing-slash `""` must
      // use the whole path, and boolean OR like `disabled || busy` where `||`
      // is the correct logical operator, not a fallback). Ignoring those two
      // primitives keeps `||` where it expresses intent while still forcing
      // `??` for the nullable-object and number cases the rule exists to catch.
      "@typescript-eslint/prefer-nullish-coalescing": [
        "error",
        { ignorePrimitives: { string: true, boolean: true } },
      ],

      // ── P5 unicorn calibrations (option-relaxations — the rule stays at
      //    `error`, the clippy.toml-threshold twin; NOT registry exceptions) ──
      //
      // React source is PascalCase components (Message.tsx, AgentModal.tsx) +
      // camelCase hooks/utils/modules (markdown.tsx, useFinderActions.ts).
      // unicorn's default kebab-case would flag every component file; allow both
      // cases so the rule still catches a genuinely mis-cased file.
      "unicorn/filename-case": ["error", { cases: { camelCase: true, pascalCase: true } }],
      // Catch bindings are `e` by house convention (a widened `unknown` since
      // P3). `ignore` lets the handful of legacy `err`/`error` names pass while
      // the rule still flags any other ad-hoc name.
      "unicorn/catch-error-name": ["error", { name: "e", ignore: ["^err$", "^error$"] }],

      // ── P5 unicorn justified disables (registered in
      //    .github/checks/allowed-eslint-exceptions.yaml; each is a
      //    React/DOM-incompatible or pure-naming-opinion rule with no
      //    correctness value — the config-level exception channel, never an
      //    inline eslint-disable) ──
      //
      // Bans idiomatic short identifiers (e, err, fn, props, params, db, ctx…)
      // — pervasive, zero correctness value, fights React/JS convention.
      "unicorn/name-replacements": "off",
      // React & the DOM use `null` intrinsically: useState<T | null>(null),
      // refs, getAttribute, DragEvent.dataTransfer. `null` is not avoidable.
      "unicorn/no-null": "off",
      // Forces is/has/should boolean-name prefixes; our booleans (dragging,
      // copied, busy, saving, open, dirty) are idiomatic React state names.
      "unicorn/consistent-boolean-name": "off",
      // Browser-only code legitimately uses `window.*` (setTimeout,
      // addEventListener, prompt); rewriting to globalThis buys nothing.
      "unicorn/prefer-global-this": "off",
      // Bans `new`/`set`-prefixed non-constructor names (newFolder, newAgent) —
      // pure naming opinion.
      "unicorn/no-non-function-verb-prefix": "off",
      // `Array.prototype.reduce` is a legitimate, readable summation idiom used
      // in the cost tables; unicorn's blanket ban is pure opinion.
      "unicorn/no-array-reduce": "off",
      // Fire-and-forget promise chains with a `.catch()` error sink are the
      // idiomatic non-blocking pattern in React sync event handlers and effect
      // bodies (which cannot be `async` — an effect must return its cleanup
      // synchronously). Forcing `await` here means wrapping every handler in a
      // `void (async () => { … })()` IIFE, a readability regression for a
      // single-level chain. The genuine anti-pattern the rule targets (nested
      // `.then()` pyramids) does not occur in this codebase.
      "unicorn/prefer-await": "off",
      // IRRECONCILABLE CONFLICT WITH PRETTIER (the canonical formatter — the
      // rustfmt twin, established in P2). unicorn/no-nested-ternary permits
      // nesting but DEMANDS the nested branch be parenthesized (`a ? b : (c ? d
      // : e)`); Prettier authoritatively strips exactly those parens as
      // redundant and reflows ternaries to its own indentation. The two fight
      // in an infinite loop (eslint --fix re-adds the parens, prettier --write
      // removes them). This rule is purely a paren-placement/readability
      // opinion — formatting that Prettier already owns — so the formatter
      // wins and the rule is off. Genuinely-complex nested ternaries were
      // still extracted into flat if-chain helpers during P5 (App.renderView,
      // StatusBar.resolvePhase, FleetDashboard.healthCondition,
      // ThreadComposer banner, ThreadList.dotColor) on readability grounds.
      "unicorn/no-nested-ternary": "off",

      // ── P6 React-stack justified disables (registered in
      //    .github/checks/allowed-eslint-exceptions.yaml; each a
      //    deliberate-UX or false-positive-only rule, config-level channel,
      //    never an inline eslint-disable) ──
      //
      // autoFocus is a DELIBERATE UX choice throughout this power-user cockpit:
      // the primary thread composer, every modal's first field (login email,
      // inline rename, New-Thread / Create-Command titles, the maintenance
      // wizard steps, the OAuth login popup) auto-focuses so the keyboard is
      // ready the instant the surface opens. jsx-a11y flags it as a screen-
      // reader-disorientation risk, a real concern for content pages — but here
      // every autoFocus sits on the sole input of a just-opened focused dialog
      // or the app's central composer, the canonical exception. Off tree-wide.
      "jsx-a11y/no-autofocus": "off",
      // @eslint-react/no-array-index-key guards against index keys on a list
      // that REORDERS/INSERTS mid-stream (React then reuses the wrong child
      // instance/state). Every dynamic, reorderable list in this app already
      // keys by a stable domain id (fleet→agent.id, threads→thread.id,
      // finder→node.path). The remaining `key={i}` sites are all STATIC,
      // wholesale-rerendered presentational lists with no per-item state —
      // syntax-highlighted code lines, sheet cells, PDF-page thumbnails,
      // waveform bars, parsed markdown/message segments, read-only inspector
      // rows (tree, radar, entities, vitals) — where the index IS the stable
      // identity and reconciliation is never wrong. The rule yields only
      // false positives against this codebase's actual usage; off tree-wide.
      // (The two genuinely interactive lists — question options, upload chips —
      // are ALSO keyed by a natural id so they stay correct regardless.)
      "@eslint-react/no-array-index-key": "off",
    },
  },
  {
    // Vendored shadcn primitives (`components/ui/**`) ship component + variant
    // table per file by design — the upstream canonical shape we don't rewrite.
    // Treated like generated code: Fast-Refresh purity is not enforced here.
    files: ["src/components/ui/**/*.{ts,tsx}"],
    rules: {
      "react-refresh/only-export-components": "off",
      // Vendored shadcn primitives keep their upstream kebab-case filenames
      // (dropdown-menu.tsx, scroll-area.tsx) and their canonical cva() call
      // nesting — both are the upstream shape we don't rewrite.
      "unicorn/filename-case": "off",
      "unicorn/max-nested-calls": "off",
    },
  },
  {
    // The WYSIWYG markdown editor drives a `contentEditable` surface through
    // `document.execCommand` / `queryCommandState`. Both are marked deprecated
    // by MDN, yet they remain the ONLY browser API for rich-text editing of a
    // contentEditable region — there is no standardised replacement (the
    // proposed `EditContext`/Input Events level 2 don't cover formatting
    // commands, and every WYSIWYG library still relies on `execCommand`). This
    // is a genuine irreducible-exception, scoped to this one file and this one
    // rule — the config-level analog of the Rust `allowed-lint-exceptions.yaml`
    // registry (never an inline `eslint-disable`, which the P4 anti-cheat layer
    // forbids). It is NOT a blanket downgrade: every other rule stays at error.
    files: ["src/components/agents/MarkdownEditor.tsx"],
    rules: {
      "@typescript-eslint/no-deprecated": "off",
    },
  },
  {
    // The Finder mock filesystem embeds Rust + JSX code SAMPLES as multiline
    // template literals for the preview pane (e.g. `format!("Sent to {tid}")`,
    // `<Finder root={root} cwd={cwd} setCwd={setCwd} />`). Those `{tid}` /
    // `{root}` braces are LITERAL text in the displayed foreign-language code,
    // not JS interpolation — unicorn/no-incorrect-template-string-interpolation
    // can't tell display text from a typo'd `${…}` and false-positives on every
    // one. Scoped off for this single mock-data file (the rule stays at error
    // everywhere else, where it genuinely catches a missing `$`).
    files: ["src/lib/support/finderFs.ts"],
    rules: {
      "unicorn/no-incorrect-template-string-interpolation": "off",
    },
  },
  {
    // hey-api's codegen config file carries the tool's CONVENTIONAL filename
    // (`openapi-ts.config.ts`, hyphenated) — it's referenced verbatim by
    // `npx @hey-api/openapi-ts -f openapi-ts.config.ts` in CB5 +
    // check-typescript-contract.sh and by tsconfig.node.json's include, so it
    // is not ours to rename. unicorn/filename-case (calibrated to camel/pascal)
    // flags the hyphen; scoped off for this single external-tool config file.
    files: ["openapi-ts.config.ts"],
    rules: {
      "unicorn/filename-case": "off",
    },
  },
  {
    // Two irreducible tooling false-positives on the Finder root, scoped to this
    // one file + these rules (the config-level exception channel, registered in
    // allowed-eslint-exceptions.yaml — never an inline eslint-disable):
    //
    // • react-hooks/refs — the Finder threads its single-click SETTLE-TIMER ref
    //   into the extracted pure handler factory `finderSelection` (a function
    //   invoked during render). finderSelection reads/writes that ref ONLY
    //   inside deferred event handlers (the setTimeout armed by onRowClick),
    //   NEVER during render, so the pass is safe by construction — but the
    //   react-compiler's conservative taint analysis can't see through the
    //   function boundary and flags it. Every other ref in the file
    //   (surfaceRef / fileInputRef / mainRef) is passed to a JSX `ref=` prop or
    //   a hook, never read in render, so the file-scoped disable masks no real
    //   ref-in-render bug.
    //
    // • jsx-a11y/no-noninteractive-{element-interactions,tabindex} — the surface
    //   is a keyboard-driven WIDGET (arrow nav, type-ahead, Space Quick-Look,
    //   Enter rename, ⌘⌫ trash) that owns its key handling, so it carries
    //   `role="application"` + `tabIndex={0}` + `onKeyDown`. `application` is the
    //   honest ARIA role for a keystroke-capturing region, but jsx-a11y models it
    //   as STRUCTURAL (non-interactive) and false-positives; the correct-looking
    //   alternative `role="grid"` would be DISHONEST (the container wraps a
    //   toolbar + sidebar + main + path bar, not a literal grid of rows/cells).
    //
    // Every other rule stays at error.
    files: ["src/components/finder/Finder.tsx"],
    rules: {
      "react-hooks/refs": "off",
      "jsx-a11y/no-noninteractive-element-interactions": "off",
      "jsx-a11y/no-noninteractive-tabindex": "off",
    },
  },
  {
    // The live code preview injects highlight.js output through
    // `dangerouslySetInnerHTML`. highlight.js ESCAPES the source text and emits
    // only class-tagged `<span>`s — there is no user-controlled HTML in the
    // string, and rendering a pre-highlighted HTML fragment is the ONLY way to
    // show syntax colours (React can't re-create highlight.js's span tree from
    // JSX). A genuine irreducible use, scoped to this one file + this one rule
    // (the config-level exception channel, registered in
    // allowed-eslint-exceptions.yaml — never an inline eslint-disable, which the
    // P4 anti-cheat layer forbids). Every other rule stays at error.
    files: ["src/components/finder/preview/livePreviews.tsx"],
    rules: {
      "@eslint-react/dom-no-dangerously-set-innerhtml": "off",
    },
  },
])
