import js from "@eslint/js"
import globals from "globals"
import reactHooks from "eslint-plugin-react-hooks"
import reactRefresh from "eslint-plugin-react-refresh"
import tseslint from "typescript-eslint"
import { defineConfig, globalIgnores } from "eslint/config"

/**
 * Frontend ESLint flat config — the Rust-parity strict stack (branch `web-lint`).
 *
 * Built as a RATCHET: plugin groups are switched on one phase at a time, each
 * landing at `error` with its violations burned down before the next is added
 * (see the P0→P13 roadmap). This file starts at the pre-existing effective
 * ruleset (P0) and grows toward ~1,100–1,400 active rules.
 *
 * `src/lib/api/generated/**` is globally ignored: it is OpenAPI codegen output
 * (regenerated by CB3/CB5), not hand-written — the analog of not linting Rust's
 * generated bindings. It must never be hand-edited to satisfy a lint.
 */
export default defineConfig([
  // Build artifacts + machine-generated code are never linted.
  globalIgnores(["dist", "src/lib/api/generated/**"]),
  {
    files: ["**/*.{ts,tsx}"],
    extends: [js.configs.recommended, tseslint.configs.recommended, reactRefresh.configs.vite],
    plugins: {
      // react-hooks is pinned to its CLASSIC rule pair for the P0 baseline
      // (rules-of-hooks + exhaustive-deps) — the exact effective ruleset before
      // this branch. The plugin's v7 `flat.recommended` additionally ships the
      // compiler-aware rules (set-state-in-effect, refs, immutability,
      // static-components, use-memo); those land deliberately in P6 (React
      // stack) with proper per-site fixes, not front-loaded into P0.
      "react-hooks": reactHooks,
    },
    languageOptions: {
      globals: globals.browser,
    },
    rules: {
      // Classic react-hooks pair (see the plugins note above).
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      // `cva()` variant tables and other module-level `const` exports sit
      // beside their component (the shadcn/vite idiom). They don't break Fast
      // Refresh, so permit them; hooks/functions co-exported with components
      // still error and get factored into sibling modules.
      "react-refresh/only-export-components": ["error", { allowConstantExport: true }],
    },
  },
  {
    // Vendored shadcn primitives (`components/ui/**`) ship component + variant
    // table per file by design — the upstream canonical shape we don't rewrite.
    // Treated like generated code: Fast-Refresh purity is not enforced here.
    files: ["src/components/ui/**/*.{ts,tsx}"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
])
