import { defineConfig } from "@hey-api/openapi-ts"

/**
 * hey-api OpenAPI → TypeScript codegen config (web-lint P1 generated-bindings).
 *
 * The generated client under `src/lib/api/generated/**` is a CONTRACT BOUNDARY:
 * our hand-written `lib/api` consumers type-check against the exported types,
 * but the vendored runtime internals are not `exactOptionalPropertyTypes`-clean
 * under the maximal-strict tsconfig, so every generated file carries a
 * `// @ts-nocheck` header excluding it from strict internal checking (the exact
 * analogue of a relaxed lint profile over Rust generated bindings).
 *
 * That header is emitted **natively** here via `output.header` (a function whose
 * lines are prepended to every generated file) rather than stamped on by a
 * post-processing step in `check-typescript-contract.sh`. Consequence: the
 * committed tree is byte-identical to a plain `npx @hey-api/openapi-ts` run —
 * `generated/**` is never hand-touched after codegen, and the contract drift
 * check simply regenerates and `git diff --exit-code`s.
 *
 * `@ts-nocheck` is placed FIRST so it sits in the file's leading comment block
 * before any code (where TypeScript honours the directive).
 */
export default defineConfig({
  input: "../openapi.json",
  output: {
    path: "src/lib/api/generated",
    header: () => [
      "// @ts-nocheck — hey-api generated client. Type-checked at the contract boundary (our hand-written lib/api consumers validate against the exported types); the vendored runtime internals are not exactOptionalPropertyTypes-clean and regenerate verbatim, so they are excluded from strict internal checking (web-lint P1, generated-bindings exception).",
      "// This file is auto-generated by @hey-api/openapi-ts",
    ],
  },
})
